// ===== 基礎補給站：公司理財＋統計先備知識 =====
DATA.basic = {
  name: '基礎', full: '基礎補給站', hue: 'basic',
  intro: '衍金、投資學會用到的公司理財與統計基本功。看不懂其他科的卡片時，先回來這裡補一下。每張卡都從零開始講，也是 CFA Level I 的地基。',
  sections: [
  { id:'b1', t:'1. 錢與時間', cards: [
    { id:'bret', t:'報酬率：賺了百分之幾？', en:'Rate of return',
      plain:'報酬率 = 賺到的錢 ÷ 一開始投入的錢。用百分比表示，才能比較大小不同的投資。',
      life:'你用 100 元買一張卡牌，後來賣 120 元，還拿到 5 元的紅利 → 賺了 25 元，報酬率 25%。',
      body:'<p class="formula">報酬率 = (期末價格 − 期初價格 + 期間收到的現金) ÷ 期初價格</p><ul><li>股票：<b>資本利得</b>（價差 capital gain）＋ <b>股利</b>（dividend）。</li><li>例：股價 50 → 55，配息 2 → (55 − 50 + 2) ÷ 50 = 14%。</li><li>為什麼要用百分比？賺 10 元的投資，若本金是 20 元（50%）和 1000 元（1%）差很多。</li></ul>' },
    { id:'bint', t:'利率、單利與複利', en:'Interest, simple vs compound',
      plain:'利率是「借錢的價格」。單利只對本金算利息；複利是「利息也會再生利息」，像滾雪球。',
      life:'存 100 元、年利率 10%：單利每年都是 10 元；複利第一年 10 元、第二年 11 元（因為本金變 110）、第三年 12.1 元……越滾越大。',
      body:'<p class="formula">單利：FV = PV × (1 + r × n)　　複利：FV = PV × (1 + r)<sup>n</sup></p><ul><li>FV（future value 終值）＝未來會變成多少；PV（present value 現值）＝現在的錢；r = 每期利率；n = 期數。</li><li>一年複利 m 次：FV = PV × (1 + r/m)<sup>m×n</sup>。m 越大，FV 越大。</li><li><b>連續複利</b>（Hull 第 4 章會用）：m 趨近無限大 → FV = PV × e<sup>rn</sup>，e ≈ 2.71828。</li><li>民法 §207 禁止「利息滾入原本」就是在限制複利。</li></ul>' },
    { id:'bpv', t:'現值：未來的錢今天值多少？', en:'Present value / time value of money',
      plain:'今天的 100 元比明年的 100 元值錢，因為今天的錢可以拿去存、賺利息。把未來的錢「折回」今天，就是現值。',
      life:'如果有人說「一年後給你 110 元」或「現在給你 100 元」，利率 10% 時兩者一樣：100 存一年剛好變 110。',
      body:'<p class="formula">PV = FV ÷ (1 + r)<sup>n</sup></p><ul><li>這就是複利公式倒過來。除以 (1 + r)<sup>n</sup> 叫做<b>折現</b>（discounting）。</li><li>例：3 年後拿 1,331 元、利率 10% → PV = 1,331 ÷ 1.1<sup>3</sup> = 1,000。</li><li>為什麼重要：股票、債券的「合理價格」都是把未來所有現金流折現加總。期貨定價（Hull Ch5）也用到。</li></ul>' },
    { id:'bannual', t:'年化：把不同期間換成「一年」來比', en:'Annualizing',
      plain:'三個月賺 2% 和一年賺 7% 哪個好？要先換成同一個期間（通常是一年）才能比。',
      life:'跑 100 公尺花 15 秒和跑 1 公里花 3 分鐘，要換成「每秒幾公尺」才能比誰快。',
      body:'<ul><li>簡單年化：季報酬 2% × 4 = 8%。</li><li>複利年化：(1 + 2%)<sup>4</sup> − 1 = 8.24%。</li><li>標準差年化：月標準差 × √12（因為變異數隨時間線性增加）。</li></ul>' }
  ]},
  { id:'b2', t:'2. 金融商品是什麼', cards: [
    { id:'bstock', t:'股票：當公司的小老闆', en:'Stock / equity',
      plain:'買股票＝買公司的一小部分所有權。公司賺錢你可以分紅（股利），公司變值錢股價會漲（資本利得）。',
      life:'和朋友合開飲料店，你出 10% 的錢，就擁有 10% 股份：賺錢分你 10%，店被收購時你也拿 10%。',
      body:'<ul><li><b>股東</b> shareholder：公司的主人，有投票權。</li><li><b>有限責任</b> limited liability：公司倒了，你最多賠掉買股票的錢，不用拿自己的房子還債。</li><li><b>剩餘請求權</b>：公司要先付員工、供應商、債權人，剩下的才是股東的 → 股東風險比較高，所以期望報酬也比較高。</li><li><b>市值</b> market cap = 股價 × 股數。</li><li><b>EPS</b> 每股盈餘 = 淨利 ÷ 股數；<b>P/E</b> 本益比 = 股價 ÷ EPS。</li></ul>' },
    { id:'bbond', t:'債券：借錢給別人的借據', en:'Bond / debt',
      plain:'買債券＝借錢給公司或政府。他們定期付你利息（票息），到期還本金。利率上升時，舊債券價格會下跌。',
      life:'你借朋友 1,000 元，他每年給你 50 元利息、三年後還 1,000。如果後來銀行利率變 8%，你這張只有 5% 的借據就沒那麼搶手，要賣掉只能打折。',
      body:'<ul><li><b>面額</b> face value、<b>票面利率</b> coupon rate、<b>到期日</b> maturity。</li><li><b>殖利率</b> yield：照現在價格買進持有到期的年報酬率。</li><li><b>價格與殖利率反向</b>：殖利率↑ → 價格↓（現值公式分母變大）。</li><li>國庫券 Treasury bill：短期政府債，常被當作「無風險」資產（R<sub>f</sub>）。</li><li>股東 vs 債權人：債權人先拿錢、報酬固定；股東後拿、報酬不固定。</li></ul>' },
    { id:'bindex', t:'股價指數、ETF、共同基金', en:'Index, ETF, mutual fund',
      plain:'指數是「一籃子股票的平均分數」，用來代表整個市場。ETF 和基金是讓你一次買下一整籃股票的工具。',
      life:'全班平均分數＝指數；買 ETF 像是「買下全班的平均成績」，不用挑誰會考好。',
      body:'<ul><li>台灣加權指數、S&amp;P 500、道瓊工業指數。</li><li>指數期貨的乘數：S&amp;P 500 期貨 $250 × 指數、Mini S&amp;P $50 × 指數、台指期 NT$200 × 指數。</li><li><b>被動投資</b>：買指數（ETF）；<b>主動投資</b>：基金經理人挑股票想贏指數。《漫步華爾街》建議多數人用被動。</li></ul>' },
    { id:'bspot', t:'現貨、遠期、期貨：差在「什麼時候交錢交貨」', en:'Spot vs forward vs futures',
      plain:'現貨＝現在付錢、現在拿貨。遠期／期貨＝現在講好價格，未來才付錢交貨。',
      life:'在超商買飲料是現貨；預購演唱會周邊（現在說好價格、下個月出貨）就是遠期。',
      body:'<ul><li><b>現貨價 S</b>（spot price）：現在馬上成交的價格。</li><li><b>期貨價 F</b>：今天約定、未來交割的價格。</li><li>為什麼 F 通常不等於 S？因為等待有成本與好處：持有現貨要付倉儲費、損失利息（所以 F 常比 S 高），有些資產會配息（讓 F 低一點）。</li></ul>' },
    { id:'blong', t:'做多、做空、放空', en:'Long and short positions',
      plain:'做多（long）＝買進，希望漲。做空（short）＝賣出，希望跌。股票的「放空」是先借股票來賣，之後再買回還。',
      life:'放空像跟朋友借一本現在賣 500 元的絕版書，先賣掉拿 500；等書價跌到 300 再買一本還他，賺 200。如果書價漲到 800 你就虧了。',
      body:'<ul><li>期貨的空頭不需要先借東西，只要簽約就是 short。</li><li>放空的最大損失理論上無限（價格可以一直漲）。</li><li>融券餘額（short interest）＝大家借券放空還沒買回的量。</li></ul>' },
    { id:'blev', t:'槓桿、融資與保證金', en:'Leverage and margin',
      plain:'槓桿＝用少少的自己的錢，控制很大的部位。賺的時候放大，虧的時候也放大。',
      life:'你只出 10 萬、跟銀行借 90 萬買 100 萬的房子。房價漲 10% → 賺 10 萬，你的本金翻倍（+100%）；跌 10% → 你的 10 萬全沒了。',
      body:'<ul><li><b>槓桿倍數</b> = 部位總值 ÷ 自有資金。</li><li><b>融資買股</b>（buying on margin）：向券商借錢買股，1929 年崩盤主因之一。</li><li>期貨保證金：只要押合約價值的一小部分（例如 5–10%）→ 天生高槓桿 → 所以要每日結算、追繳保證金來控制違約風險。</li></ul>' }
  ]},
  { id:'b3', t:'3. 風險的數學', cards: [
    { id:'bmean', t:'平均數與期望值', en:'Mean and expected value',
      plain:'平均數＝過去資料加總 ÷ 個數。期望值＝未來各種可能結果 × 機率，再加總（「長期平均下來」會得到多少）。',
      life:'擲骰子的期望值 = (1+2+3+4+5+6)/6 = 3.5，雖然你從來擲不出 3.5，但擲很多次平均就是 3.5。',
      body:'<p class="formula">E(R) = Σ p<sub>i</sub> × R<sub>i</sub></p><ul><li>Σ 唸作 sigma，意思是「全部加起來」。</li><li>例：景氣好（機率 0.3）賺 20%、普通（0.5）賺 10%、差（0.2）賠 5% → 0.3×20 + 0.5×10 + 0.2×(−5) = 10%。</li></ul>' },
    { id:'bsd', t:'變異數與標準差：晃得多大？', en:'Variance and standard deviation',
      plain:'標準差 σ 衡量「結果離平均有多遠」，數字越大代表越不穩定，就是投資學說的「風險」。',
      life:'兩個同學平均都考 70 分：A 每次都 68–72（σ 小，很穩），B 有時 40 有時 100（σ 大，很不穩）。',
      body:'<p class="formula">σ² = Σ p<sub>i</sub> (R<sub>i</sub> − E(R))²　　σ = √σ²</p><ul><li>步驟：① 每個結果減平均 ② 平方（讓負的變正的）③ 乘機率（或除以個數）加總 = 變異數 ④ 開根號 = 標準差（單位回到 %）。</li><li>Hull 的 σ<sub>S</sub>、σ<sub>F</sub> 就是「價格變動」的標準差。</li></ul>' },
    { id:'bcorr', t:'共變異數與相關係數：兩個東西會不會一起動？', en:'Covariance and correlation',
      plain:'相關係數 ρ 介於 −1 到 1：1 = 完全同方向一起動；0 = 沒關係；−1 = 完全反方向。',
      life:'冰淇淋銷量和氣溫：ρ 接近 1。雨傘銷量和晴天：ρ 接近 −1。你的考試成績和隔壁班的午餐：ρ ≈ 0。',
      body:'<p class="formula">ρ = Cov(X, Y) ÷ (σ<sub>X</sub> × σ<sub>Y</sub>)</p><ul><li>共變異數 Cov：兩者偏離平均的方向是否一致（正 = 同向）。但它的數字大小沒有上限，不好比較 → 除以兩個標準差，就變成 −1 到 1 的相關係數。</li><li>避險比率 h* = ρσ<sub>S</sub>/σ<sub>F</sub> 裡的 ρ 就是它：相關越高，期貨越能幫你避險。</li></ul>' },
    { id:'bdiv', t:'分散投資：系統風險 vs 非系統風險', en:'Diversification',
      plain:'買很多支不同的股票，個別公司的意外（非系統風險）會互相抵消；但整個市場一起跌（系統風險）是分散不掉的。',
      life:'不要把雞蛋放在同一個籃子：一個籃子掉了還有別的。但如果整台車翻了（金融海嘯），所有籃子都會掉。',
      body:'<ul><li><b>非系統風險</b>（公司特有、可分散）：工廠失火、CEO 醜聞。</li><li><b>系統風險</b>（市場風險、不可分散）：利率、經濟衰退、戰爭。</li><li>因為非系統風險可以免費消除，市場只會給「系統風險」報酬 → 這就是 CAPM 只看 β 的原因。</li></ul>' },
    { id:'bbeta', t:'β 貝他：跟著大盤晃動的倍數', en:'Beta',
      plain:'β 衡量一支股票（或組合）對大盤的敏感度。β = 1 跟大盤一樣；β = 2 大盤漲 1% 它約漲 2%；β = 0.5 只漲 0.5%。',
      life:'大盤是船，β 是你坐的位置：船頭（β 高）晃得最厲害，船中間（β 低）比較穩。',
      body:'<p class="formula">β = Cov(R<sub>i</sub>, R<sub>M</sub>) ÷ σ<sub>M</sub>²</p><ul><li>β 只衡量<b>系統風險</b>。</li><li>組合的 β = 各股票 β 依權重加權平均。</li><li>用指數期貨可以把組合 β 調高或調低（衍金 Ch3）。</li></ul>' },
    { id:'bsharpe', t:'夏普比率：每承擔 1 單位風險，多賺多少？', en:'Sharpe ratio',
      plain:'夏普比率 = (報酬 − 無風險利率) ÷ 標準差。越高越好，代表「CP 值」越高。',
      life:'兩個打工：A 時薪 200 但很累，B 時薪 180 但很輕鬆。要看「每單位辛苦換到多少錢」。',
      body:'<p class="formula">Sharpe = (R<sub>p</sub> − R<sub>f</sub>) ÷ σ<sub>p</sub></p><ul><li>投資學的「績效評估」要做風險調整，夏普比率是最常用的一個。CML 的斜率就是市場組合的夏普比率。</li><li>其他：Treynor = (R<sub>p</sub> − R<sub>f</sub>)/β；Jensen α = 實際報酬 − CAPM 預期報酬。</li></ul>' }
  ]},
  { id:'b4', t:'4. 公司理財基本功', cards: [
    { id:'bdec', t:'公司的三大財務決策', en:'Three financial decisions',
      plain:'投資決策（錢花在哪）、融資決策（錢從哪來：借錢或找股東）、股利決策（賺的錢發給股東還是留著）。',
      life:'開咖啡店：買哪台咖啡機（投資）、跟銀行貸款還是找朋友入股（融資）、年底賺的錢要分紅還是拿去開分店（股利）。',
      body:'<ul><li>Investment decision、Financing decision、Dividend decision（投資學第一週講義）。</li><li>目標：讓股東財富（股價）最大化。</li></ul>' },
    { id:'bbs', t:'資產負債表：公司「有什麼、欠什麼」', en:'Balance sheet',
      plain:'資產 = 負債 + 股東權益。左邊是公司擁有的東西，右邊是這些東西的錢從哪裡來。',
      life:'你有一台 3 萬的機車（資產），其中 2 萬是跟爸媽借的（負債）、1 萬是自己存的（權益）。',
      body:'<ul><li><b>資產</b> assets：現金、存貨、廠房設備。</li><li><b>負債</b> liabilities：借款、應付帳款、發行的債券。</li><li><b>股東權益</b> equity：股東投入的錢＋累積保留的盈餘。</li><li><b>資本結構</b>：負債 vs 權益的比例。負債多 → 槓桿高、風險高。</li></ul>' },
    { id:'bis', t:'損益表：公司「這段期間賺多少」', en:'Income statement',
      plain:'營收 − 成本 − 費用 − 利息 − 稅 = 淨利。淨利 ÷ 股數 = EPS。',
      life:'飲料店一個月：賣飲料收 30 萬（營收）− 茶葉杯子 10 萬（成本）− 房租薪水 12 萬（費用）− 貸款利息 1 萬 − 稅 1 萬 = 淨利 6 萬。',
      body:'<ul><li>技術分析的優點之一（Reilly）：財報有很多種費用與資產的報告方式，技術分析不受影響。</li><li>網路泡沫時很多公司「營收有、淨利是負的」→ 本益比算不出來。</li></ul>' },
    { id:'bforms', t:'公司的法律型態與有限責任', en:'Legal forms and limited liability',
      plain:'獨資、合夥：老闆要負無限責任（賠到自己的房子）。公司：股東只負有限責任，但公司賺錢要先繳公司稅，股東領股利再繳個人稅（雙重課稅）。',
      life:'自己擺攤（獨資）欠錢要自己還；開成股份有限公司，公司欠的錢不會追到你家。',
      body:'<p>管理學 Ch10 的 Exhibit 10.2 會詳細比較：Sole proprietorship、General partnership、LLP、C corporation、S corporation、LLC。CFA Level I Corporate Issuers 也考同樣的內容。</p>' },
    { id:'barb', t:'套利與單一價格法則', en:'Arbitrage and the law of one price',
      plain:'同樣的東西在兩個地方價格不同，就可以「低買高賣」賺無風險的錢。大家都這樣做，價格就會被拉回一致。',
      life:'A 店飲料 20 元、B 店收購 25 元 → 一直買 A 賣 B，A 會漲價、B 會降價，直到差價消失。',
      body:'<ul><li>衍生性商品定價的核心：如果期貨價格偏離「合理價格」，套利者會把它拉回來。</li><li>期貨到期時一定收斂到現貨價格，就是因為套利。</li></ul>' }
  ]}
  ],
  mcq: [
    {q:'股價從 40 漲到 44，期間配息 2 元，報酬率是？', o:['10%','15%','5%','12%'], a:1, e:'(44 − 40 + 2) ÷ 40 = 6 ÷ 40 = 15%。'},
    {q:'100 元存 2 年、年利率 10%、每年複利一次，2 年後變成？', o:['120','121','110','122'], a:1, e:'100 × 1.1² = 121。單利才是 120。'},
    {q:'複利和單利的差別在於：', o:['複利的利率比較高','複利的利息也會再生利息','單利不用繳稅','沒有差別'], a:1, e:'利滾利。'},
    {q:'2 年後的 121 元，利率 10% 時的現值是？', o:['100','110','121','90'], a:0, e:'121 ÷ 1.1² = 100。'},
    {q:'利率上升時，未來固定金額的現值會：', o:['上升','下降','不變','變成 0'], a:1, e:'分母 (1 + r)ⁿ 變大，現值變小。'},
    {q:'季報酬 3%，用簡單年化大約是？', o:['3%','9%','12%','36%'], a:2, e:'3% × 4 = 12%。'},
    {q:'買股票的人是公司的：', o:['債權人','股東（所有者）','員工','供應商'], a:1, e:'買債券才是債權人。'},
    {q:'「有限責任」的意思是：', o:['股東最多賠掉投資的金額','公司不用繳稅','股東不能投票','債權人不能求償'], a:0, e:'公司的債務不會追到股東個人財產。'},
    {q:'債券的殖利率上升時，價格會：', o:['上升','下降','不變','先升後降'], a:1, e:'價格與殖利率反向。'},
    {q:'某公司淨利 1 億元、股數 1,000 萬股、股價 200 元。本益比是？', o:['10','20','2','200'], a:1, e:'EPS = 10；P/E = 200 ÷ 10 = 20。'},
    {q:'現在付錢、現在交貨的價格叫做：', o:['期貨價','現貨價','執行價','交割價'], a:1, e:'Spot price。'},
    {q:'預期價格會下跌，應該：', o:['做多','做空','買 call','什麼都不做'], a:1, e:'Short 希望跌。'},
    {q:'自己出 20 萬、借 80 萬買 100 萬的資產，槓桿倍數是？', o:['2 倍','4 倍','5 倍','10 倍'], a:2, e:'100 ÷ 20 = 5 倍。'},
    {q:'承上，資產價格下跌 10%，自有資金虧損幾 %？', o:['10%','20%','50%','80%'], a:2, e:'虧 10 萬 ÷ 20 萬 = 50%（槓桿放大 5 倍）。'},
    {q:'三種情況報酬 20%、10%、−5%，機率 0.3、0.5、0.2。期望報酬是？', o:['8.33%','10%','11%','12.5%'], a:1, e:'6 + 5 − 1 = 10%。'},
    {q:'標準差越大代表：', o:['報酬越高','結果越不穩定（風險越大）','越安全','相關係數越高'], a:1, e:''},
    {q:'變異數是 0.04，標準差是？', o:['0.0016','0.02','0.2','2'], a:2, e:'√0.04 = 0.2 = 20%。'},
    {q:'相關係數 ρ = −1 代表：', o:['完全同方向','完全反方向','沒有關係','資料錯誤'], a:1, e:'範圍 −1 到 1。'},
    {q:'Cov(X,Y) = 0.006、σX = 0.1、σY = 0.2，相關係數是？', o:['0.03','0.3','0.6','0.12'], a:1, e:'0.006 ÷ (0.1 × 0.2) = 0.3。'},
    {q:'下列何者屬於「非系統風險」？', o:['央行升息','經濟衰退','某公司工廠失火','戰爭'], a:2, e:'公司特有、可以分散。'},
    {q:'分散投資可以消除：', o:['系統風險','非系統風險','所有風險','通膨'], a:1, e:'系統風險分散不掉。'},
    {q:'β = 1.5 的股票，大盤上漲 2%，它預期大約上漲？', o:['1.5%','2%','3%','3.5%'], a:2, e:'1.5 × 2% = 3%。'},
    {q:'組合 60% 投資 β=1.2、40% 投資 β=0.7，組合 β 是？', o:['0.95','1.0','1.9','0.84'], a:1, e:'0.6×1.2 + 0.4×0.7 = 0.72 + 0.28 = 1.0。'},
    {q:'R_p = 12%、R_f = 2%、σ = 20%，夏普比率是？', o:['0.6','0.5','0.1','2'], a:1, e:'(12 − 2) ÷ 20 = 0.5。'},
    {q:'資產負債表的恆等式：', o:['資產 = 負債 − 權益','資產 = 負債 + 股東權益','淨利 = 營收 − 資產','權益 = 資產 + 負債'], a:1, e:''},
    {q:'公司決定「要跟銀行借錢還是發新股」屬於：', o:['投資決策','融資決策','股利決策','行銷決策'], a:1, e:''},
    {q:'淨利 ÷ 流通股數 = ？', o:['P/E','EPS','ROE','市值'], a:1, e:'每股盈餘。'},
    {q:'同一商品 A 市場 100 元、B 市場 105 元，套利者會：', o:['A 賣 B 買','A 買 B 賣','兩邊都買','什麼都不做'], a:1, e:'低買高賣。'},
    {q:'獨資商號的老闆對債務負：', o:['有限責任','無限責任','不負責','由政府負責'], a:1, e:''},
    {q:'C corporation 被稱為「雙重課稅」是因為：', o:['一年課兩次','公司所得與股東股利都要課稅','只有大公司要繳','需要兩個會計師'], a:1, e:''}
  ],
  match: [['spot price','現貨價'],['futures price','期貨價'],['present value','現值'],['future value','終值'],['compound interest','複利'],['dividend','股利'],['capital gain','資本利得'],['shareholder','股東'],['creditor','債權人'],['limited liability','有限責任'],['bond yield','殖利率'],['EPS','每股盈餘'],['market cap','市值'],['leverage','槓桿'],['short selling','放空'],['standard deviation','標準差'],['correlation','相關係數'],['covariance','共變異數'],['beta','系統風險敏感度'],['diversification','分散投資'],['systematic risk','不可分散的市場風險'],['Sharpe ratio','每單位風險的超額報酬'],['risk-free rate','無風險利率'],['balance sheet','資產負債表'],['income statement','損益表'],['arbitrage','套利']],
  sort: [
    { t:'系統風險還是非系統風險？', b:['系統風險（分散不掉）','非系統風險（可分散）'], items:[['央行升息',0],['某公司 CEO 醜聞',1],['全球金融海嘯',0],['某工廠火災',1],['戰爭爆發',0],['某藥廠新藥失敗',1],['經濟衰退',0],['某公司產品召回',1]] },
    { t:'資產、負債還是股東權益？', b:['資產','負債','股東權益'], items:[['現金',0],['銀行借款',1],['股東投入的資本',2],['廠房設備',0],['發行的公司債',1],['保留盈餘',2],['存貨',0],['應付帳款',1]] },
    { t:'這是哪一種財務決策？', b:['投資決策','融資決策','股利決策'], items:[['要不要蓋新工廠',0],['發行公司債',1],['今年配多少現金股利',2],['併購一家公司',0],['辦理現金增資',1],['把盈餘保留下來再投資',2]] }
  ]
};

DATA.basic.formulas = [
  { id:'B1', t:'報酬率', en:'Holding period return', q:'這筆投資賺了百分之幾？',
    tex:'<v s="R">R</v> = (<v s="P1">P<sub>1</sub></v> − <v s="P0">P<sub>0</sub></v> + <v s="D">D</v>) ÷ <v s="P0">P<sub>0</sub></v>',
    syms:{R:['報酬率','holding period return','這段期間賺了幾 %'],P1:['期末價格','ending price','賣出（或現在）的價格'],P0:['期初價格','beginning price','買進的價格'],D:['期間收到的現金','income (dividend / coupon)','股利或利息']},
    why:'分子是「總共賺到多少錢」：價差（P<sub>1</sub> − P<sub>0</sub>）加上中間拿到的現金 D。分母是本金。除完就是「每 1 元本金賺了多少」。',
    steps:['價差 = P<sub>1</sub> − P<sub>0</sub>','加上股利 D','÷ P<sub>0</sub>','× 100%'],
    vars:[{k:'P0',s:'P<sub>0</sub>',v:50,min:1,max:500,step:1},{k:'P1',s:'P<sub>1</sub>',v:55,min:0,max:500,step:1},{k:'D',s:'D',v:2,min:0,max:50,step:0.5}],
    calc:v=>`(${v.P1} − ${v.P0} + ${v.D}) ÷ ${v.P0} = ${fx(v.P1-v.P0+v.D)} ÷ ${v.P0} = <b>${fx((v.P1-v.P0+v.D)/v.P0*100,2)}%</b>`,
    oops:['分母用期末價格','忘了加股利'], exam:'The holding period return is (P<sub>1</sub> − P<sub>0</sub> + D)/P<sub>0</sub>.', cfa:'CFA Level I Quant：holding period return。' },
  { id:'B2', t:'複利終值', en:'Future value with compounding', q:'現在的錢放 n 年後會變成多少？',
    tex:'<v s="FV">FV</v> = <v s="PV">PV</v> × (1 + <v s="r">r</v>)<sup><v s="n">n</v></sup>',
    syms:{FV:['終值','future value','未來會變成多少'],PV:['現值','present value','現在投入的錢'],r:['每期利率','interest rate per period','例如年利率 5% = 0.05'],n:['期數','number of periods','放幾年（幾期）']},
    why:'每過一期，錢都乘上 (1 + r)。過 n 期就乘 n 次 → (1 + r)<sup>n</sup>。這就是「利滾利」：第二年的利息是用「本金＋第一年利息」來算。',
    steps:['1 + r','算 n 次方','× PV'],
    vars:[{k:'PV',s:'PV',v:100,min:1,max:100000,step:1},{k:'r',s:'r (%)',v:10,min:0,max:30,step:0.5},{k:'n',s:'n',v:3,min:0,max:40,step:1}],
    calc:v=>`${v.PV} × (1 + ${v.r/100})<sup>${v.n}</sup> = ${v.PV} × ${fx(Math.pow(1+v.r/100,v.n))} = <b>${fx(v.PV*Math.pow(1+v.r/100,v.n),2)}</b>（單利只有 ${fx(v.PV*(1+v.r/100*v.n),2)}）`,
    oops:['把 (1 + r)<sup>n</sup> 算成 1 + r × n（那是單利）','利率忘了換成小數'], exam:'With annual compounding, FV = PV(1 + r)<sup>n</sup>.', cfa:'CFA Level I Quant：time value of money（超級基礎）。' },
  { id:'B3', t:'現值（折現）', en:'Present value', q:'未來的錢，今天值多少？',
    tex:'<v s="PV">PV</v> = <v s="FV">FV</v> ÷ (1 + <v s="r">r</v>)<sup><v s="n">n</v></sup>',
    syms:{PV:['現值','present value','今天值多少'],FV:['未來金額','future value','未來會拿到的錢'],r:['折現率','discount rate','你要求的報酬率／利率'],n:['期數','periods','幾年後拿到']},
    why:'就是複利公式倒過來。問自己：「今天要存多少，n 年後才會變成 FV？」答案就是 FV 除以成長倍數。利率越高、等越久，現值越小。',
    steps:['(1 + r)<sup>n</sup>','FV ÷ 它'],
    vars:[{k:'FV',s:'FV',v:1331,min:1,max:100000,step:1},{k:'r',s:'r (%)',v:10,min:0,max:30,step:0.5},{k:'n',s:'n',v:3,min:0,max:40,step:1}],
    calc:v=>`${v.FV} ÷ ${fx(Math.pow(1+v.r/100,v.n))} = <b>${fx(v.FV/Math.pow(1+v.r/100,v.n),2)}</b>`,
    oops:['乘以 (1 + r)<sup>n</sup>（方向反了）'], exam:'The present value of a future cash flow is FV/(1 + r)<sup>n</sup>.', cfa:'CFA Level I：discounted cash flow 的基礎。' },
  { id:'B4', t:'期望報酬', en:'Expected return', q:'考慮各種可能，平均會賺多少？',
    tex:'<v s="E">E(R)</v> = Σ <v s="p">p<sub>i</sub></v> × <v s="R">R<sub>i</sub></v>',
    syms:{E:['期望報酬','expected return','長期平均'],p:['第 i 種情況的機率','probability','全部加起來 = 1'],R:['第 i 種情況的報酬','return in state i','']},
    why:'每種情況「出現的次數比例」乘上「那時候的報酬」再加總，就是加權平均。',
    steps:['每種情況：機率 × 報酬','全部加起來'],
    vars:[{k:'p1',s:'好 機率',v:0.3,min:0,max:1,step:0.05},{k:'r1',s:'好 報酬%',v:20,min:-50,max:80,step:1},{k:'p2',s:'普通 機率',v:0.5,min:0,max:1,step:0.05},{k:'r2',s:'普通 報酬%',v:10,min:-50,max:80,step:1},{k:'r3',s:'差 報酬%',v:-5,min:-80,max:50,step:1}],
    calc:v=>{const p3=+(1-v.p1-v.p2).toFixed(2);return `差的機率 = 1 − ${v.p1} − ${v.p2} = ${p3}<br>${v.p1}×${v.r1} + ${v.p2}×${v.r2} + ${p3}×(${v.r3}) = <b>${fx(v.p1*v.r1+v.p2*v.r2+p3*v.r3,2)}%</b>`;},
    oops:['機率加總不等於 1'], exam:'Expected return is the probability-weighted average of possible returns.', cfa:'CFA Quant：expected value。' },
  { id:'B5', t:'標準差', en:'Standard deviation', q:'報酬晃動得多厲害（風險多大）？',
    tex:'<v s="s">σ</v> = √[ Σ <v s="p">p<sub>i</sub></v> × (<v s="R">R<sub>i</sub></v> − <v s="E">E(R)</v>)² ]',
    syms:{s:['標準差','standard deviation','風險的大小'],p:['機率','probability',''],R:['各情況報酬','return in state i',''],E:['期望報酬','expected return','平均']},
    why:'① 每個結果跟平均差多少（R − E）。② 有正有負會互相抵消，所以先平方。③ 用機率加權平均 → 變異數。④ 平方後單位變成「%²」很奇怪，開根號回到 % → 標準差。',
    steps:['算 E(R)','每個 R − E(R)','平方','× 機率後加總 = 變異數','開根號'],
    vars:[{k:'r1',s:'情況1 報酬%',v:20,min:-50,max:80,step:1},{k:'r2',s:'情況2 報酬%',v:0,min:-50,max:80,step:1}],
    calc:v=>{const E=(v.r1+v.r2)/2;const var_=((v.r1-E)**2+(v.r2-E)**2)/2;return `兩種情況各 50%：E = ${fx(E,2)}%<br>σ² = 0.5×(${v.r1}−${fx(E,2)})² + 0.5×(${v.r2}−${fx(E,2)})² = ${fx(var_,2)}　→ σ = <b>${fx(Math.sqrt(var_),2)}%</b>`;},
    oops:['忘了開根號','沒平方直接加（正負抵消變 0）'], exam:'Standard deviation measures the dispersion of returns around the mean and is used as a measure of total risk.', cfa:'CFA Quant：variance and standard deviation。' },
  { id:'B6', t:'相關係數', en:'Correlation coefficient', q:'兩個資產是不是一起漲跌？',
    tex:'<v s="r">ρ</v> = <v s="c">Cov(X,Y)</v> ÷ (<v s="sx">σ<sub>X</sub></v> × <v s="sy">σ<sub>Y</sub></v>)',
    syms:{r:['相關係數','correlation','−1 到 1'],c:['共變異數','covariance','一起偏離平均的程度'],sx:['X 的標準差','σ of X',''],sy:['Y 的標準差','σ of Y','']},
    why:'共變異數有方向但沒有固定刻度（單位一換數字就變），除以兩個標準差就把它「標準化」成 −1～1，可以直接比較。',
    steps:['算 Cov','算 σ<sub>X</sub>、σ<sub>Y</sub>','相除'],
    vars:[{k:'c',s:'Cov',v:0.006,min:-0.05,max:0.05,step:0.001},{k:'sx',s:'σ<sub>X</sub>',v:0.1,min:0.01,max:1,step:0.01},{k:'sy',s:'σ<sub>Y</sub>',v:0.2,min:0.01,max:1,step:0.01}],
    calc:v=>{const r=v.c/(v.sx*v.sy);return `${v.c} ÷ (${v.sx} × ${v.sy}) = <b>${fx(r,3)}</b>${Math.abs(r)>1?'（超過 ±1，這組數字不可能存在）':''}`;},
    oops:['忘了乘兩個標準差'], exam:'Correlation equals covariance divided by the product of the two standard deviations; it ranges from −1 to +1.', cfa:'CFA Quant＋Portfolio：covariance、correlation。' },
  { id:'B7', t:'兩資產組合的報酬與風險', en:'Two-asset portfolio', q:'把錢分成兩份投資，整體報酬與風險是多少？',
    tex:'<v s="Rp">E(R<sub>p</sub>)</v> = <v s="w">w</v>R<sub>1</sub> + (1−<v s="w">w</v>)R<sub>2</sub><br><v s="sp">σ<sub>p</sub>²</v> = w²σ<sub>1</sub>² + (1−w)²σ<sub>2</sub>² + 2w(1−w)<v s="r">ρ</v>σ<sub>1</sub>σ<sub>2</sub>',
    syms:{Rp:['組合期望報酬','portfolio expected return','加權平均'],w:['投資在資產 1 的比例','weight','0～1'],sp:['組合變異數','portfolio variance','開根號 = 組合標準差'],r:['相關係數','correlation','越小 → 分散效果越好']},
    why:'報酬就是簡單的加權平均。風險卻<b>不是</b>加權平均：多了最後一項「2w(1−w)ρσ<sub>1</sub>σ<sub>2</sub>」。ρ 越小（甚至負的），這一項越小，組合風險就比兩個單獨的都低 → 這就是分散投資的數學。',
    steps:['報酬：權重 × 報酬，加總','風險：代入三項','開根號'],
    vars:[{k:'w',s:'w',v:0.5,min:0,max:1,step:0.05},{k:'s1',s:'σ<sub>1</sub>%',v:20,min:0,max:60,step:1},{k:'s2',s:'σ<sub>2</sub>%',v:30,min:0,max:60,step:1},{k:'r',s:'ρ',v:0.2,min:-1,max:1,step:0.05}],
    calc:v=>{const w=v.w,a=v.s1/100,b=v.s2/100;const vp=w*w*a*a+(1-w)**2*b*b+2*w*(1-w)*v.r*a*b;return `σ<sub>p</sub>² = ${fx(w*w*a*a)} + ${fx((1-w)**2*b*b)} + ${fx(2*w*(1-w)*v.r*a*b)} = ${fx(vp)}<br>σ<sub>p</sub> = <b>${fx(Math.sqrt(Math.max(vp,0))*100,2)}%</b>（加權平均會是 ${fx((w*a+(1-w)*b)*100,2)}%，差距就是分散的好處）`;},
    oops:['把組合標準差當成加權平均'], exam:'Portfolio risk is lower than the weighted average of individual risks whenever the correlation is less than +1.', cfa:'CFA Level I Portfolio Management：必考。' },
  { id:'B8', t:'夏普比率', en:'Sharpe ratio', q:'每承擔 1 單位總風險，多賺多少？',
    tex:'<v s="S">Sharpe</v> = (<v s="Rp">R<sub>p</sub></v> − <v s="rf">R<sub>f</sub></v>) ÷ <v s="s">σ<sub>p</sub></v>',
    syms:{S:['夏普比率','Sharpe ratio','風險調整後的績效'],Rp:['組合報酬','portfolio return',''],rf:['無風險利率','risk-free rate',''],s:['組合標準差','portfolio standard deviation','總風險']},
    why:'R<sub>p</sub> − R<sub>f</sub> 是「比放定存多賺的部分」（超額報酬），除以「承擔的風險」。像比較兩份打工的「時薪」，而不是只看總薪水。',
    steps:['超額報酬 = R<sub>p</sub> − R<sub>f</sub>','÷ σ<sub>p</sub>'],
    vars:[{k:'Rp',s:'R<sub>p</sub>%',v:12,min:-20,max:50,step:0.5},{k:'rf',s:'R<sub>f</sub>%',v:2,min:0,max:10,step:0.25},{k:'s',s:'σ<sub>p</sub>%',v:20,min:1,max:60,step:1}],
    calc:v=>`(${v.Rp} − ${v.rf}) ÷ ${v.s} = <b>${fx((v.Rp-v.rf)/v.s,3)}</b>`,
    oops:['用 β 當分母（那是 Treynor）'], exam:'The Sharpe ratio measures excess return per unit of total risk.', cfa:'CFA Level I：Sharpe ratio 必考。' },
  { id:'B9', t:'貝他', en:'Beta', q:'這支股票對大盤有多敏感？',
    tex:'<v s="b">β<sub>i</sub></v> = <v s="c">Cov(R<sub>i</sub>, R<sub>M</sub>)</v> ÷ <v s="v">σ<sub>M</sub>²</v> = <v s="r">ρ<sub>iM</sub></v> × <v s="si">σ<sub>i</sub></v> ÷ <v s="sm">σ<sub>M</sub></v>',
    syms:{b:['貝他','beta',''],c:['與市場的共變異數','covariance with market',''],v:['市場變異數','market variance',''],r:['與市場的相關係數','correlation with market',''],si:['股票標準差','stock σ',''],sm:['市場標準差','market σ','']},
    why:'把 Cov 換成 ρσ<sub>i</sub>σ<sub>M</sub> 就得到第二個寫法。發現了嗎？它跟衍金的 h* = ρσ<sub>S</sub>/σ<sub>F</sub> 長得一模一樣！所以用指數期貨避險時，β 就是避險比率。',
    steps:['ρ × σ<sub>i</sub>','÷ σ<sub>M</sub>'],
    vars:[{k:'r',s:'ρ',v:0.8,min:-1,max:1,step:0.05},{k:'si',s:'σ<sub>i</sub>%',v:30,min:1,max:80,step:1},{k:'sm',s:'σ<sub>M</sub>%',v:20,min:1,max:60,step:1}],
    calc:v=>`${v.r} × ${v.si} ÷ ${v.sm} = <b>${fx(v.r*v.si/v.sm,3)}</b>`,
    oops:['除以 σ<sub>M</sub> 而不是 σ<sub>M</sub>²（用 Cov 的寫法時）'], exam:'Beta equals the covariance of the asset with the market divided by the variance of the market.', cfa:'CFA Level I：beta、CAPM 必考。' }
];
