// ===== 管理學（Robbins & Coulter） =====
DATA.mgmt = {
  name: '管理學', full: '管理學', hue: 'mgmt',
  intro: 'Robbins & Coulter《Management》14/15 版。期中考 11/4（第 9 週），範圍到 Ch11 組織設計。會有申論題 → 下方「申論練習」可拍照上傳手寫答案，讓 Claude 依評分要點批改。',
  sections: [
  { id:'m1', t:'Ch1 管理者與職場', cards: [
    { id:'m1a', t:'誰是管理者？三個層級', en:'Who is a manager',
      plain:'管理者＝協調並監督他人工作、讓組織達成目標的人。分基層、中階、高階。',
      life:'學生會：活動組組長（基層，帶組員）、部長（中階，帶組長）、會長（高階，決定整年方向）。',
      fig:'pyramid',
      body:'<ul><li><b>First-line managers 基層</b>：管理非管理職員工。</li><li><b>Middle managers 中階</b>：管理基層管理者。</li><li><b>Top managers 高階</b>：做全組織決策、建立計畫與目標。</li><li><b>Organization 組織</b>：為達特定目的而刻意安排的一群人；三特徵：<b>distinct purpose 明確目的、deliberate structure 刻意結構、people 人</b>。</li><li>管理者為何重要：不確定、複雜、混亂時更需要；完成事情的關鍵；影響員工生產力與忠誠（不投入的管理者因員工流動造成數十億損失）。</li></ul>' },
    { id:'m1b', t:'效率 vs 效能', en:'Efficiency vs Effectiveness',
      plain:'效率＝把事情做對（用最少投入得到最多產出，看手段）；效能＝做對的事情（達成目標，看結果）。',
      life:'用最省油的方式開車（效率），但開錯目的地（沒效能）。好的管理兩者兼具。',
      fig:'effeff',
      body:'<ul><li><b>Efficiency: doing things right</b> — resource usage, low waste → <b>means</b></li><li><b>Effectiveness: doing the right things</b> — goal attainment, high attainment → <b>ends</b></li></ul>' },
    { id:'m1c', t:'管理四大功能 POLC', en:'Planning, Organizing, Leading, Controlling',
      plain:'規劃（定目標與策略）→ 組織（安排工作與結構）→ 領導（透過人完成目標）→ 控制（監督、比較、修正）。',
      life:'辦一場畢業旅行：決定去哪、預算（規劃）；分工訂車訂房（組織）；鼓勵大家準時集合（領導）；檢查行程有沒有照計畫、預算有沒有超支（控制）。',
      fig:'polc',
      body:'<ul><li><b>Planning</b>: defining goals, establishing strategies, developing plans</li><li><b>Organizing</b>: arranging and structuring work</li><li><b>Leading</b>: working with and through people</li><li><b>Controlling</b>: monitoring, comparing, and correcting work</li></ul>' },
    { id:'m1d', t:'Mintzberg 十種管理角色', en:"Mintzberg's 10 roles",
      plain:'人際角色（代表人、領導者、聯絡人）、資訊角色（監控者、傳播者、發言人）、決策角色（企業家、問題處理者、資源分配者、談判者）。',
      life:'班長：參加典禮代表全班（代表人）、帶大家做事（領導者）、跟別班聯絡（聯絡人）、收集同學意見（監控）、轉達老師消息（傳播）、對外發言（發言人）、提議新活動（企業家）、處理吵架（問題處理）、分配班費（資源分配）、跟老師爭取延後考試（談判）。',
      fig:'mintz',
      body:'<ul><li><b>Interpersonal</b>：Figurehead、Leader、Liaison（人與儀式／象徵性責任）</li><li><b>Informational</b>：Monitor、Disseminator、Spokesperson（收集、接收、傳遞資訊）</li><li><b>Decisional</b>：Entrepreneur、Disturbance handler、Resource allocator、Negotiator（做選擇）</li></ul>' },
    { id:'m1e', t:'Katz 三種管理技能', en:"Katz's skills",
      plain:'技術技能（專業知識）、人際技能（跟人合作）、概念技能（看全局、抽象思考）。越高階越需要概念技能；越基層越需要技術技能；人際技能各層都重要。',
      life:'基層店員要會操作收銀機（技術）；店長要會排班安撫員工（人際）；區域總監要看懂整個商圈趨勢（概念）。',
      fig:'katz',
      body:'<ul><li>Technical skills：job-specific knowledge and techniques</li><li>Human skills：ability to work well with people</li><li>Conceptual skills：think and conceptualize about abstract and complex situations</li></ul>' },
    { id:'m1f', t:'今日管理者的挑戰與為何學管理', en:'Challenges / Why study',
      plain:'挑戰：科技、破壞式創新、社群媒體、倫理、政治不確定、顧客。學管理的理由：管理具普遍性、你不是管人就是被管、有回報也有挑戰。',
      life:'就算你以後當工程師，也會有主管、也可能帶專案小組。',
      body:'<ul><li>Focus on technology、disruptive innovation（汽車摧毀馬車業）、social media、ethics（藥廠漲價 500%、假收據）、political uncertainty（Brexit、USMCA、加州額外規範）、customer。</li><li><b>Universality of management</b>：所有類型、規模、層級、部門、地點的組織都需要管理。</li><li>The reality of work：you will either manage or be managed。</li><li>Rewards（Exhibit 1.9）：創造好的工作環境、發揮創意、幫他人找到意義、教練與培育、與多元的人合作、獲得認可與地位、影響組織結果、薪資獎金股票選擇權。</li><li><b>Employability Skills Matrix (ESM)</b>：Critical thinking、Communication、Collaboration、Knowledge application and analysis、Social responsibility。</li></ul>' }
  ]},
  { id:'m2', t:'Ch2 決策', cards: [
    { id:'m2a', t:'決策八步驟', en:'8-step decision-making process',
      plain:'辨識問題 → 決策準則 → 給準則權重 → 列方案 → 分析方案 → 選方案 → 執行 → 評估效果。',
      life:'Amanda 要幫業務買筆電：問題 = 舊筆電不夠用；準則 = 記憶體、電池、重量、保固、螢幕；權重 10/8/6/4/3；列 7 台；每台評分 × 權重；選最高分（Surface Book / 14 版 Dell Inspiron 249 分）。',
      fig:'w:decision',
      body:'<ol><li>Identify a problem（現況與期望狀態的差距）</li><li>Identify decision criteria</li><li>Allocate weights to the criteria</li><li>Develop alternatives</li><li>Analyze alternatives</li><li>Select an alternative</li><li>Implement the alternative（傳達決策、取得承諾）</li><li>Evaluate decision effectiveness</li></ol>' },
    { id:'m2b', t:'決策方式：理性、有限理性、直覺、證據、群眾外包', en:'Approaches',
      plain:'理性決策假設資訊完整、目標清楚；現實是有限理性，只求「夠好」(satisfice)。也可靠直覺、靠證據、靠群眾。',
      life:'買手機：理性 = 把所有型號比完；有限理性 = 看了三支覺得這支夠好就買；直覺 = 憑感覺；證據 = 看評測數據；群眾外包 = 上 Dcard 問網友。',
      body:'<ul><li><b>Rational</b>：logical, consistent, maximize value。假設：決策者邏輯客觀、問題清楚明確、目標清楚且知道所有方案與後果、會選最大化方案、以組織最佳利益決策。</li><li><b>Bounded rationality</b>：受限於處理資訊的能力 → <b>Satisfice</b>。</li><li><b>Escalation of commitment 承諾升高</b>（14 版）：有證據顯示錯了仍加碼。</li><li><b>Intuitive</b>：基於經驗、感覺、累積的判斷（五面向：experienced-based、affect-initiated、cognitive-based、values or ethics-based、subconscious mental processing）。</li><li><b>Evidence-based management (EBMgt)</b>：系統化使用最佳可得證據。</li><li><b>Crowdsourcing</b>（15 版）：向傳統決策者之外的網絡徵求意見。</li></ul>' },
    { id:'m2c', t:'問題與決策的類型', en:'Programmed vs Nonprogrammed',
      plain:'結構化問題 → 程式化決策（用程序、規則、政策處理）；非結構化問題 → 非程式化決策（客製化、靠判斷與創意）。',
      life:'顧客要退貨 → 照 SOP（程式化）；公司要不要進軍東南亞 → 高層要動腦（非程式化）。',
      body:'<table class="tbl"><tr><th></th><th>Programmed</th><th>Nonprogrammed</th></tr><tr><td>問題</td><td>Structured</td><td>Unstructured</td></tr><tr><td>層級</td><td>Lower</td><td>Upper</td></tr><tr><td>頻率</td><td>Repetitive</td><td>New, unusual</td></tr><tr><td>資訊</td><td>Readily available</td><td>Ambiguous, incomplete</td></tr><tr><td>目標</td><td>Clear, specific</td><td>Vague</td></tr><tr><td>時間</td><td>Short</td><td>Relatively long</td></tr><tr><td>依靠</td><td>Procedures, rules, policies</td><td>Judgment and creativity</td></tr></table><ul><li><b>Procedure</b> 一系列步驟；<b>Rule</b> 明確告訴能/不能做什麼；<b>Policy</b> 決策的指導方針。</li></ul>' },
    { id:'m2d', t:'決策情境：確定、風險、不確定（14 版）', en:'Certainty / Risk / Uncertainty',
      plain:'確定＝結果都知道；風險＝能估機率 → 算期望值；不確定＝連機率都估不出 → 依個性選樂觀（maximax）、悲觀（maximin）、最小遺憾（minimax regret）。',
      life:'買彩券：知道機率是風險；第一次去陌生國家創業，連機率都不知道是不確定。',
      fig:'w:payoffm',
      body:'<ul><li>期望值例：大雪 850,000×0.3、普通 725,000×0.5、小雪 350,000×0.2 → 總期望營收 687,500（講義表格中 362,000 應為 362,500）。</li><li>Visa vs MasterCard 報酬矩陣：樂觀者選最大值中的最大（S4 = 28）；悲觀者選最小值中的最大（S3 最小 15）；遺憾矩陣 → 每欄最大值（24、21、28）減各格 → 選最大遺憾最小的 S4（最大遺憾 7）。</li></ul>' },
    { id:'m2e', t:'四種決策風格', en:'Decision-making styles',
      plain:'兩個維度：思考方式（理性 vs 直覺）×模糊容忍度（低 vs 高）。',
      life:'Directive：喜歡快速明確的答案；Analytic：要更多資料再決定；Conceptual：看長期大局；Behavioral：重視大家的感受與共識。',
      fig:'styles',
      body:'<ul><li><b>Directive</b>：低模糊容忍、理性</li><li><b>Analytic</b>：高模糊容忍、理性</li><li><b>Conceptual</b>：高模糊容忍、直覺</li><li><b>Behavioral</b>：低模糊容忍、直覺</li></ul>' },
    { id:'m2f', t:'12 種決策偏誤', en:'Biases and errors',
      plain:'捷思法（rule of thumb）能幫忙，也會造成偏誤。',
      life:'沉沒成本：電影很難看但「票都買了」硬看完；錨定：店家先標原價 3000 再打 5 折，你就覺得 1500 很便宜。',
      fig:'w:bias',
      body:'<p>Overconfidence、Immediate gratification、Anchoring、Selective perception、Confirmation、Framing、Availability、Representation、Randomness、Sunk costs、Self-serving、Hindsight。下方互動卡可逐一翻看例子。</p>' },
    { id:'m2g', t:'有效決策與前沿工具', en:'Effective & cutting-edge',
      plain:'有效決策過程：聚焦重要事、邏輯一致、融合分析與直覺、資訊夠用就好、蒐集相關資訊、簡單可靠有彈性。新工具：設計思考、大數據、AI。',
      life:'設計思考像設計師做產品：先觀察使用者、原型、測試，而不是只坐在辦公室算數字。',
      body:'<ul><li>Guidelines（14 版）：了解文化差異、建立好決策標準、知道何時該放棄、使用有效決策流程、培養清楚思考能力。</li><li><b>Design thinking</b>：approaching management problems as designers approach design problems。</li><li><b>Big data</b>：善於找相關性，但無法說明哪些相關有意義 → 需要好的判斷。</li><li><b>AI</b>：Machine learning（自動建立分析模型）、Deep learning（多層人工神經網路模擬大腦）、Analytics（數學、統計、預測模型找模式）。</li></ul>' }
  ]},
  { id:'m4', t:'Ch4 全球環境中的管理', cards: [
    { id:'m4a', t:'全球觀：三種態度', en:'Ethnocentric / Polycentric / Geocentric',
      plain:'民族中心（母國做法最好）、多元中心（地主國經理最懂當地）、全球中心（全世界最好的做法都拿來用）。',
      life:'台灣老闆去日本開店：堅持台灣做法（民族中心）；全交給日本店長（多元中心）；兩邊優點都用（全球中心）。',
      body:'<ul><li><b>Globalization</b>：在他國發展影響力或營運的過程。</li><li><b>Nationalism</b>：頌揚本國價值的愛國理想與政策。</li><li><b>Parochialism 狹隘主義</b>：只用自己的觀點看世界，無法辨識差異。</li></ul>' },
    { id:'m4b', t:'全球化歷史與機構', en:'Mechanisms & milestones',
      plain:'一戰後保護主義、二戰後走向全球化；WTO、IMF、世界銀行、GATT、OECD、ASEAN、EU、NAFTA→USMCA；近年鐘擺擺回民族主義。',
      life:'鐘擺：一下全球化（大家互相買賣），一下民族主義（築高牆課關稅）。',
      fig:'pendulum',
      body:'<ul><li><b>WTO</b>：161 國，處理國際貿易規則，取代 GATT。</li><li><b>IMF</b>：188 國，促進國際貨幣合作，提供建議、貸款、技術協助。</li><li><b>World Bank Group</b>：對開發中國家提供財務與技術協助。</li><li><b>GATT</b>：1948 年減少或消除貿易障礙的協定。</li><li><b>OECD</b>：協助 34 會員國永續成長與就業。</li><li><b>ASEAN</b>：10 個東南亞國家貿易聯盟。<b>EU</b>：28 國、歐元。<b>NAFTA</b>：墨、加、美 → <b>USMCA</b>（2018）。</li><li>里程碑：World Economic Forum（1974）、柴契爾（1979）與雷根（1980）支持自由貿易、蘇聯解體（1991）、上海合作組織（2003）、We are the 99%（2011）、中國製造 2025（2015）、Brexit、川普 America First、TPP 瓦解（2016）、USMCA（2018）。</li></ul>' },
    { id:'m4c', t:'支持與反對全球化', en:'For and against',
      plain:'支持：比較利益法則 → 每個國家都贏（水漲船高）。反對：工作流向低工資國、中產階級薪資停滯、貧富不均擴大。管理意涵：全球化會持續，基礎建設已在，失業主因是科技。',
      life:'台灣專心做晶片、越南專心做成衣，再互相交換，兩邊都更有效率；但台灣成衣工人可能失業。',
      body:'<ul><li>The Win-Win Argument：law of comparative advantage — 專注於機會成本最低的產品再交易。</li><li>The Downside：jobs leaving high-labor-cost nations、wage stagnation、wealth inequality。</li></ul>' },
    { id:'m4d', t:'國際組織類型與走向國際的方式', en:'Types & going global',
      plain:'MNC（多國營運）→ 多國內（權力下放當地）、全球（集中母國）、跨國／無疆界（去除地理界線）。進入方式由低到高投入：全球採購 → 進出口 → 授權、加盟 → 策略聯盟、合資 → 海外子公司。',
      life:'珍奶店出海：只進口原料（全球採購）、出口茶葉（出口）、讓外國人用你的品牌開店（加盟）、跟當地公司合開新公司（合資）、自己去設分公司（子公司）。',
      fig:'goglobal',
      body:'<ul><li>Multidomestic：decentralizes to local country；Global：centralizes in home country；Transnational/borderless：eliminated artificial geographical barriers。</li><li><b>Licensing</b>：給他人製造或銷售產品的權利（技術、規格）— 常見於製造業；<b>Franchising</b>：給他人使用名稱與營運方法 — 常見於服務業。</li><li><b>Strategic alliance</b>：共享資源與知識；<b>Joint venture</b>：成立獨立新組織；<b>Foreign subsidiary</b>：直接投資設立獨立廠房或辦公室。</li></ul>' },
    { id:'m4e', t:'政治法律、經濟、文化環境', en:'PEST-like environments',
      plain:'要懂當地法律與政治穩定性；經濟是自由市場還是計畫經濟（匯率、通膨、稅）；文化用 Hofstede 五構面或 GLOBE 九構面分析。',
      life:'入境隨俗（When in Rome, do as the Romans do）。',
      fig:'hofstede',
      body:'<ul><li>Free market economy（私部門擁有控制）vs Planned economy（中央政府規劃）。</li><li><b>National culture</b>：一國人民共享的價值與態度。Exhibit 4.4 美國人特質：非正式、直接、競爭、成就導向、獨立個人主義、重視個人空間、討厭沉默、守時、重視清潔。</li><li><b>Hofstede 五構面</b>：Individualism–Collectivism、Power distance、Uncertainty avoidance、Achievement–Nurturing（masculinity）、Long-term vs Short-term orientation。</li><li><b>GLOBE 九構面</b>：Power distance、Uncertainty avoidance、Assertiveness、Humane orientation、Future orientation、Institutional collectivism、Gender differentiation、In-group collectivism、Performance orientation。</li></ul>' }
  ]},
  { id:'m7', t:'Ch7 變革與破壞式創新', cards: [
    { id:'m7a', t:'變革的理由與力量', en:'Forces for change',
      plain:'組織變革＝人、結構、技術的任何改變。變革推手（change agent）負責管理過程。外部力量：顧客、法律、科技、經濟；內部力量：新策略、人力組成、新設備、員工態度。',
      life:'VUCA：Volatility、Uncertainty、Complexity、Ambiguity — 現在唯一不變的就是變。',
      body:'<ul><li>External：consumer needs and wants、new governmental laws、technology、the economy</li><li>Internal：new organizational strategy、composition of the workforce、new equipment、employee attitudes</li></ul>' },
    { id:'m7b', t:'平靜水域 vs 激流泛舟；Lewin 三步驟', en:'Calm waters vs White-water',
      plain:'平靜水域：變革是偶發事件 → 解凍、改變、再凍結。激流泛舟：環境一直變，要持續適應。',
      life:'平靜水域像搬家（一次搬完再安頓）；激流泛舟像在急流中划船，每一秒都要調整。',
      fig:'lewin',
      body:'<ul><li><b>Lewin</b>：Unfreezing the status quo（增加驅動力、減少抑制力）→ Changing → Refreezing。</li><li>White-water rapids：lack of stability and predictability requires continual adaptation。</li></ul>' },
    { id:'m7c', t:'四種變革領域', en:'Strategy / Structure / Technology / People',
      plain:'策略（成功的方法）、結構（設計）、技術（流程設備、自動化、電腦化）、人（態度、行為；組織發展 OD）。',
      life:'餐廳轉型：改賣外送（策略）、合併廚房與外場（結構）、導入點餐 App（技術）、訓練員工服務態度（人）。',
      body:'<ul><li><b>Organizational development (OD)</b>：聚焦人與人際工作關係的變革方法（Exhibit 7.4：survey feedback、process consultation、team-building、intergroup development 等）。</li></ul>' },
    { id:'m7d', t:'抗拒變革與降低抗拒的六種方法', en:'Resistance to change',
      plain:'人抗拒變革因為：不確定、習慣、怕失去、認為違反組織目標。降低方法：教育溝通、參與、協助支持、談判、操縱與收編、強制。',
      life:'學校要改用新系統：開說明會（教育）、讓學生代表一起規劃（參與）、開教學課程（協助）、給早鳥優惠（談判）、找人氣學長背書（收編）、直接規定期限（強制）。',
      body:'<table class="tbl"><tr><th>方法</th><th>何時用</th><th>優點</th><th>缺點</th></tr><tr><td>Education &amp; communication</td><td>抗拒源於錯誤資訊</td><td>澄清誤解</td><td>缺乏信任時無效</td></tr><tr><td>Participation</td><td>抗拒者有專業可貢獻</td><td>增加投入與接受</td><td>耗時、可能產生差方案</td></tr><tr><td>Facilitation &amp; support</td><td>抗拒者恐懼焦慮</td><td>協助調適</td><td>昂貴、不保證成功</td></tr><tr><td>Negotiation</td><td>抗拒來自有力群體</td><td>可「買到」承諾</td><td>成本高、他人也會施壓</td></tr><tr><td>Manipulation &amp; co-optation</td><td>需要有力群體背書</td><td>便宜容易</td><td>可能反噬、失去信用</td></tr><tr><td>Coercion</td><td>需要有力群體背書</td><td>便宜容易</td><td>可能違法、損害信用</td></tr></table>' },
    { id:'m7e', t:'改變組織文化；員工壓力', en:'Culture & Stress',
      plain:'文化穩定難改，但在危機、領導更替、組織年輕小、文化弱時較容易。壓力來源：任務、角色（衝突、過載、模糊）、人際、結構、領導；個人因素 A 型 vs B 型性格。',
      life:'公司換新 CEO 正是改變文化的好時機。',
      body:'<ul><li>Exhibit 7.6：高層以身作則、新故事符號儀式、選拔升遷支持新價值者、重新設計社會化、改變獎酬、明確期望取代潛規則、輪調打散次文化、參與與高度信任。</li><li><b>Stress</b>：對過度壓力的不良反應；<b>Stressors</b>：造成壓力的因素。症狀：生理、心理、行為。</li><li>減壓：甄選時的實際工作預覽、績效規劃（MBO）、工作再設計、諮商、時間管理、健康計畫。</li></ul>' },
    { id:'m7f', t:'創意 vs 創新；激發創新的三類變數', en:'Creativity & Innovation',
      plain:'創意＝把想法用獨特方式組合；創新＝把創意變成有用的產品或方法。激發創新：結構、文化、人力資源三類變數。',
      life:'想到「可以邊走邊喝的湯」是創意；做出能量產的杯湯是創新。',
      fig:'innov',
      body:'<ul><li>Structural：organic structures、abundant resources、high interunit communication、minimal time pressure、work and nonwork support。</li><li>Cultural：acceptance of ambiguity、tolerance of the impractical、low external controls、tolerance of risks、tolerance of conflict、focus on ends、open-system focus、positive feedback。</li><li>HR：<b>idea champion</b>（積極支持新想法、建立支持、克服抗拒、確保落實）。</li><li>最創新企業：Apple、Netflix、Square、Tencent、Amazon。</li></ul>' },
    { id:'m7g', t:'破壞式創新 vs 維持式創新', en:'Disruptive vs Sustaining',
      plain:'破壞式創新徹底改變產業遊戲規則；維持式創新只是小幅改良。大型、成熟、高獲利的企業最脆弱，因為最捨不得現有市場。',
      life:'Netflix 打敗百視達、Uber 衝擊計程車、Wikipedia 取代百科全書。',
      body:'<ul><li>Exhibit 7.9：CD → iTunes、複寫紙 → Xerox、帆布鞋 → Nike、收音機 → Walkman → iPod、打字機 → IBM PC、週刊 → CNN、電視台 → 有線/Netflix、旅行社 → Expedia、股票經紀 → eTrade、旅行支票 → ATM/Visa、百科全書 → Wikipedia、分類廣告 → Craigslist、AM/FM → Sirius XM、報稅服務 → TurboTax、黃頁 → Google、紙地圖 → Garmin GPS、平裝書 → Kindle、律師 → LegalZoom、計程車 → Uber。</li><li>Implications：創業者、企業管理者（<b>Skunk works</b>：大組織中高度自主、不受官僚束縛的小團隊，專做激進創新）、生涯規劃。</li></ul>' }
  ]},
  { id:'m9', t:'Ch9 策略管理', cards: [
    { id:'m9a', t:'策略管理六步驟', en:'Strategic management process',
      plain:'確認使命目標策略 → 外部分析（機會威脅）→ 內部分析（優勢劣勢）→ 擬定策略 → 執行 → 評估結果。前三步合起來就是 SWOT。',
      life:'準備考研究所：先確認目標學校（使命）、看今年錄取率與題型（外部）、評估自己強弱科（內部）、排讀書計畫（擬定）、照表操課（執行）、模擬考檢討（評估）。',
      fig:'swot',
      body:'<ul><li><b>Strategic management</b>：管理者發展組織策略所做的事。<b>Strategies</b>：如何經營、競爭、吸引滿足顧客的計畫。<b>Business model</b>：公司如何賺錢。</li><li>重要性：正面影響績效、幫助面對變化與不確定、讓複雜多元的組織協同。</li><li>Mission：組織的目的。</li><li>Resources（資產）、Capabilities（能力）、<b>Core competencies</b>（主要創造價值的能力 = 競爭武器）。</li></ul>' },
    { id:'m9b', t:'三層策略與公司層級策略', en:'Corporate / Competitive / Functional',
      plain:'公司層級：要做哪些事業（成長、穩定、更新）。競爭層級：每個事業怎麼競爭。功能層級：各部門如何支援。',
      life:'統一集團：決定要不要經營超商、藥妝、物流（公司層級）；7-11 用便利性競爭（競爭層級）；行銷部辦集點活動（功能層級）。',
      body:'<ul><li><b>Growth</b>：Concentration 集中（本業擴大）、Vertical integration 垂直整合（向上游供應商或下游通路）、Horizontal integration 水平整合（併購同業）、Diversification 多角化（相關或非相關）。</li><li><b>Stability</b>：維持現狀。</li><li><b>Renewal</b>：績效衰退時 — Retrenchment 緊縮（小問題）、Turnaround 轉型（嚴重問題）。</li></ul>' },
    { id:'m9c', t:'BCG 矩陣', en:'BCG matrix',
      plain:'用「市場成長率」×「市場占有率」把事業單位分成明星、金牛、問號、狗。',
      life:'明星 = 當紅偶像（高成長高市佔，要繼續投資）；金牛 = 長青老店（低成長高市佔，提供現金）；問號 = 新人（高成長低市佔，要決定培養或放棄）；狗 = 過氣（低成長低市佔，考慮出售）。',
      fig:'bcg',
      body:'<p>BCG matrix：a strategy tool that guides resource allocation decisions on the basis of market share and growth rate of SBUs。</p>' },
    { id:'m9d', t:'競爭優勢、經濟護城河、Porter 五力', en:'Competitive advantage',
      plain:'競爭優勢＝讓你與眾不同的獨特優勢（品質、低成本、技術）。護城河（巴菲特）＝長期保護利潤與市佔的方法。五力決定產業吸引力。',
      life:'台積電的先進製程就是護城河：別人很難追上。',
      fig:'five',
      body:'<ul><li>Porter 五力：Threat of new entrants、Threat of substitutes、Bargaining power of buyers、Bargaining power of suppliers、Current rivalry。</li><li><b>SBU</b>：組織中各自擬定競爭策略的獨立事業單位。</li></ul>' },
    { id:'m9e', t:'Porter 三大競爭策略', en:'Generic strategies',
      plain:'成本領導（全產業最低成本）、差異化（獨特、顧客願意多付）、集中（專攻某個利基市場，再用成本或差異化）。兩頭不到岸 = stuck in the middle。',
      life:'全聯（成本領導）、星巴克（差異化）、專做左撇子文具的店（集中）。',
      body:'<ul><li>差異化例子：Quality、Innovation（技術移轉、R&amp;D、流程改善、<b>First mover</b>）、Customer service、Mass customization、Social media。</li><li><b>First mover 優點</b>：品牌聲譽、技術領先、搶占資源、建立轉換成本、學習曲線；<b>缺點</b>：不確定市場方向、高開發成本、技術被模仿或被新技術取代、需教育市場。</li><li>Functional strategies：支援競爭策略的部門策略。</li></ul>' }
  ]},
  { id:'m10', t:'Ch10 創業', cards: [
    { id:'m10a', t:'創業 vs 小企業 vs 自僱', en:'Entrepreneurship',
      plain:'創業＝回應機會開新事業，追求創新、成長與獲利。小企業主想「謀生」，看到風險；創業家想「改變世界」，看到機會。自僱＝為自己的事業工作賺錢。',
      life:'開巷口早餐店（小企業）vs 做出全台連鎖早餐 App 平台（創業）。',
      body:'<ul><li>重要性：Innovation、Economic growth、Job creation、Global entrepreneurship。</li><li>創業流程：探索創業情境 → 辨識機會與競爭優勢 → 開始創業 → 管理事業。</li><li>Hybrid path：保留正職、副業開始創業 → 壓力小、存活率高（過半新創 4 年內失敗）。</li></ul>' },
    { id:'m10b', t:'機會來源與可行性研究', en:'Opportunities & Feasibility',
      plain:'Drucker 七大機會來源：意外、不一致、流程需求、產業市場結構、人口變化、認知改變、新知識。找點子要看：現有限制、新方法、突破、未滿足利基、趨勢。',
      life:'疫情（意外）帶來外送平台機會；高齡化（人口）帶來長照商機。',
      body:'<ul><li>Exhibit 10.1：個人考量（能力、準備、情緒、面對失敗、努力、實際認知、持續分析）、市場考量（顧客、產品特色、通路、定價、推廣、融資）。</li><li><b>Feasibility study</b>：分析新事業各面向以判斷可行性。競爭者分析：產品、優缺點、行銷定價通路、差異化。</li><li>融資：<b>Venture capitalists</b>（專業管理的投資資金池，外部股權）、<b>Angel investors</b>（私人投資者換股權）、<b>IPO</b>（首次公開發行）。</li><li><b>Business plan</b>：Executive summary、Analysis of opportunity、Analysis of the context、Description of the business、Financial data and projections、Supporting documentation。</li></ul>' },
    { id:'m10c', t:'六種法律組織形式', en:'Legal forms',
      plain:'獨資、普通合夥、有限責任合夥（LLP）、C 公司、S 公司、有限責任公司（LLC）。主要考量：稅與法律責任。',
      life:'自己擺攤（獨資，賠了要拿自己的房子還）vs 開公司（有限責任，最多賠掉投資的錢）。',
      body:'<table class="tbl"><tr><th>形式</th><th>責任</th><th>稅</th><th>重點</th></tr><tr><td>Sole proprietorship</td><td>無限</td><td>穿透，個人稅率</td><td>成本低、完全控制、易退出</td></tr><tr><td>General partnership</td><td>無限</td><td>穿透</td><td>資源人才合併；決策分歧、衝突</td></tr><tr><td>LLP</td><td>有限（至少一人無限）</td><td>穿透</td><td>向有限合夥人籌資；有限合夥人不能經營</td></tr><tr><td>C corporation</td><td>有限</td><td><b>雙重課稅</b></td><td>可轉讓、永續存在；設立貴、管制多</td></tr><tr><td>S corporation</td><td>有限</td><td>穿透（像合夥）</td><td>最多 75 名股東</td></tr><tr><td>LLC</td><td>有限</td><td>穿透</td><td>彈性大；需 operating agreement</td></tr></table><p>Closely held corporation：少數人擁有、不公開交易股票。</p>' },
    { id:'m10d', t:'創業者的組織、領導與控制', en:'Organizing / Leading / Controlling',
      plain:'組織設計六要素；人資：招募與留才。領導：主動人格、賦權員工；三階段：新創 → 轉型（要學授權）→ 擴張。控制：看數字、盯競爭、聯繫顧客、監控員工績效與負荷。退場：收割（harvesting）。',
      life:'早餐店從老闆一人包辦（新創）到請店長管理（轉型）到開分店（擴張）。',
      body:'<ul><li><b>Proactive personality</b>：傾向採取行動影響環境。</li><li>Exhibit 10.3 優勢：Risk、Knowledge、Independence、Confidence、Delegation、Determination、Relationships、Selling、Profitability、Disruption。</li><li>五種退場：併購、賣給友好買家、IPO、當金牛、清算。</li><li>估值方法：Asset、Earnings、Cash-flow valuations。</li></ul>' }
  ]},
  { id:'m11', t:'Ch11 組織結構設計', cards: [
    { id:'m11a', t:'組織設計六要素', en:'Six elements',
      plain:'工作專業化、部門化、指揮鏈、控制幅度、集權/分權、正式化。',
      life:'手搖飲店：有人專門封膜（專業化）、分外場內場（部門化）、店員向店長報告（指揮鏈）、一個店長管 8 人（控制幅度）、新品由總部決定（集權）、SOP 寫得很細（正式化）。',
      fig:'org6',
      body:'<ul><li><b>Work specialization</b>：分工；有經濟性也有不經濟性（過度 → 無聊、疲勞、壓力、品質差、缺勤）。</li><li><b>Departmentalization</b> 五種：Functional、Geographic、Product、Process、Customer。趨勢：<b>cross-functional teams</b>、customer departmentalization。</li><li><b>Chain of command</b>；<b>Authority</b>（line authority 直線職權 vs staff authority 幕僚職權）；<b>Responsibility</b>；<b>Unity of command</b>：每人只向一位主管報告。</li><li><b>Span of control</b>：一位主管能有效管理的人數。幅度 4 vs 8：較寬者少兩層、約少 800 位管理者。</li><li><b>Centralization</b> vs <b>Decentralization</b>；<b>Employee empowerment</b>。</li><li><b>Formalization</b>：工作標準化程度、受規則程序引導程度。</li></ul>' },
    { id:'m11b', t:'集權 vs 分權的時機', en:'When centralize',
      plain:'環境穩定、基層能力不足或不想參與、決策小、危機、公司大 → 集權。環境複雜不確定、基層有能力且想參與、決策重大、文化開放、地理分散 → 分權。',
      life:'颱風來襲停班停課 → 由上面統一決定（集權）；各分店自行決定當天促銷品（分權）。',
      body:'<p>Exhibit 11.5 對照：More centralization — stable environment、lower-level managers not as capable、do not want a say、minor decisions、crisis、large company、strategy depends on top retaining say。More decentralization — complex uncertain environment、capable、want a voice、significant decisions、open culture、geographically dispersed、strategy depends on managers’ involvement。</p>' },
    { id:'m11c', t:'機械式 vs 有機式組織', en:'Mechanistic vs Organic',
      plain:'機械式：僵硬、嚴格控制（高專業化、部門僵固、指揮鏈清楚、窄幅度、集權、高正式化）。有機式：高度彈性（跨職能團隊、跨層級、資訊自由流動、寬幅度、分權、低正式化）。',
      life:'機械式像軍隊或麥當勞廚房；有機式像新創公司或設計工作室。',
      fig:'mechorg',
      body:'<ul><li>權變因素：<b>策略</b>（創新 → 有機；成本 → 機械）、<b>規模</b>（大 → 機械，但超過某規模影響變小）、<b>技術</b>、<b>環境不確定性</b>（穩定簡單 → 機械；越不確定 → 有機）。</li><li><b>Woodward</b>：Unit production（小批量）→ 有機；Mass production（大量）→ 機械；Process production（連續流程）→ 有機。</li></ul><table class="tbl"><tr><th></th><th>Unit</th><th>Mass</th><th>Process</th></tr><tr><td>垂直分化</td><td>低</td><td>中</td><td>高</td></tr><tr><td>水平分化</td><td>低</td><td>高</td><td>低</td></tr><tr><td>正式化</td><td>低</td><td>高</td><td>低</td></tr><tr><td>最有效</td><td>Organic</td><td>Mechanistic</td><td>Organic</td></tr></table>' },
    { id:'m11d', t:'傳統與現代組織設計', en:'Design options',
      plain:'傳統：簡單結構、功能結構、事業部結構。現代：團隊結構、矩陣與專案結構、虛擬組織；彈性工作：遠距、壓縮工時、彈性工時、工作分享、臨時人力。',
      life:'矩陣結構：你同時屬於「設計部」又屬於「A 專案」，有兩個主管（違反指揮統一）。',
      fig:'matrix',
      body:'<ul><li><b>Simple</b>：少部門化、寬幅度、集權於一人、低正式化（快速彈性、責任清楚；成長後不適用、依賴一人）。</li><li><b>Functional</b>：依職能分組（專業化成本優勢；部門本位、看不見整體目標）。</li><li><b>Divisional</b>：半自主事業部（聚焦結果；活動資源重複、成本高、效率低）。</li><li><b>Team</b>：整個組織由工作團隊組成。<b>Matrix</b>：把不同職能部門的專家指派到專案。<b>Project</b>：員工持續在專案間工作。</li><li><b>Virtual (network/modular)</b>：小核心全職員工＋依需求臨時聘外部專家。</li><li><b>Telecommuting</b>、<b>Compressed workweek</b>（每天工時長、天數少）、<b>Flextime</b>（固定總時數、時段可變）、<b>Job sharing</b>（兩人以上分擔一份全職）、<b>Contingent workers</b>（臨時、自由接案、約聘）。</li></ul>' }
  ]}
  ],
  essays: [
    {q:'請說明「效率」與「效能」的差異，並以一個你熟悉的組織為例，說明管理者如何同時兼顧兩者。', ch:'Ch1', pts:['效率 = doing things right，手段，資源使用、低浪費','效能 = doing the right things，目的，目標達成','兩者關係：好的管理同時兼具；可能有效率卻無效能','具體例子並說明管理者的做法']},
    {q:'試述 Mintzberg 的十種管理角色，並舉例說明一位店長在一天中如何扮演這些角色。', ch:'Ch1', pts:['三大類：人際、資訊、決策','人際：代表人、領導者、聯絡人','資訊：監控者、傳播者、發言人','決策：企業家、問題處理者、資源分配者、談判者','每類至少有對應的店長例子']},
    {q:'Katz 提出管理者需具備哪三種技能？不同層級管理者對這些技能的需求有何不同？', ch:'Ch1', pts:['技術、人際、概念技能的定義','基層最需技術技能、高層最需概念技能','人際技能各層級都同等重要','舉例或圖示']},
    {q:'請說明決策制定的八個步驟，並以一個實際決策（例如選擇實習公司）逐步應用。', ch:'Ch2', pts:['八步驟順序正確','權重與評分的計算邏輯','執行與評估回饋','例子完整貫穿']},
    {q:'比較理性決策與有限理性決策，並說明「滿意解（satisficing）」與「承諾升高（escalation of commitment）」的意義。', ch:'Ch2', pts:['理性決策的假設（問題清楚、目標明確、知道所有方案、選最大化）','有限理性：受資訊處理能力限制','Satisfice：接受夠好的方案','承諾升高：有錯誤證據仍加碼，例子']},
    {q:'比較程式化決策與非程式化決策，並說明程序、規則、政策三者的差異。', ch:'Ch2', pts:['結構化 vs 非結構化問題','層級、頻率、資訊、目標、時間、依靠的差異','Procedure、Rule、Policy 定義與例子']},
    {q:'選擇三種你認為最常見的決策偏誤，說明其意義、舉例，並提出管理者如何避免。', ch:'Ch2', pts:['偏誤名稱與正確定義','生活或企業例子','具體的避免方法（如找反方意見、設停損點）']},
    {q:'說明管理者對外國市場的三種態度（民族中心、多元中心、全球中心），並評論何者較適合今日的跨國企業。', ch:'Ch4', pts:['三種態度定義','各自優缺點','論證全球中心的適用性與限制']},
    {q:'企業走向國際化有哪些方式？請依投入程度由低至高說明，並比較授權與加盟。', ch:'Ch4', pts:['全球採購、進出口、授權、加盟、策略聯盟、合資、海外子公司','投入與風險遞增','Licensing（技術、製造）vs Franchising（名稱、營運方法、服務業）']},
    {q:'請說明支持與反對全球化的論點，並討論近年民族主義回潮（如 Brexit、USMCA）對管理者的意涵。', ch:'Ch4', pts:['比較利益法則、雙贏','工作外移、薪資停滯、不均','鐘擺效應與具體事件','管理意涵（全球化仍持續、需全球管理技能）']},
    {q:'以 Hofstede 的文化構面比較台灣與美國，說明一位美籍主管來台灣管理時可能遇到的問題。', ch:'Ch4', pts:['五構面名稱正確','台美差異（如權力距離、個人主義）','具體管理問題與建議']},
    {q:'比較「平靜水域」與「激流泛舟」兩種變革觀點，並說明 Lewin 的三步驟變革模型。', ch:'Ch7', pts:['平靜水域：變革是偶發中斷','激流泛舟：持續變動需不斷適應','解凍、改變、再凍結','驅動力與抑制力']},
    {q:'員工為何抗拒變革？請說明六種降低抗拒的方法，並各說明其適用時機與缺點。', ch:'Ch7', pts:['四個抗拒原因','六種方法完整','適用時機','優缺點']},
    {q:'何謂破壞式創新？為何大型成熟企業最容易受威脅？請舉例並說明企業可如何因應（如 skunk works）。', ch:'Ch7', pts:['定義與維持式創新的差異','大型企業最捨不得既有市場與技術','具體例子','因應方法']},
    {q:'說明組織中刺激創新的結構、文化與人力資源變數。', ch:'Ch7', pts:['結構：有機、資源充足、跨單位溝通、時間壓力低、支持','文化：接受模糊、容忍不切實際、低外部控制、容忍風險與衝突、重結果、開放系統、正向回饋','人資：idea champion']},
    {q:'說明策略管理的六個步驟，並以一家企業為例進行 SWOT 分析。', ch:'Ch9', pts:['六步驟','核心能力、資源與能力','SWOT 四象限具體內容','導出策略']},
    {q:'說明公司層級的三種策略，並解釋 BCG 矩陣如何協助資源分配。', ch:'Ch9', pts:['成長（集中、垂直、水平、多角化）、穩定、更新（緊縮、轉型）','BCG 四象限定義','各象限的資源處置']},
    {q:'說明 Porter 的五力分析與三種競爭策略，並以一個產業為例說明。', ch:'Ch9', pts:['五力名稱','成本領導、差異化、集中','stuck in the middle','產業例子連結']},
    {q:'比較創業與經營小企業的差異，並說明創業者在規劃新事業時需做哪些可行性研究。', ch:'Ch10', pts:['機會 vs 風險、改變世界 vs 謀生','機會來源','可行性：點子、競爭者、融資（VC、天使、IPO）','營運計畫書要項']},
    {q:'比較獨資、合夥、C 公司、LLC 的責任與課稅，並建議一位剛畢業的創業者應選哪一種。', ch:'Ch10', pts:['責任：無限 vs 有限','稅：穿透 vs 雙重課稅','優缺點','合理建議']},
    {q:'說明組織設計的六大要素，並比較機械式與有機式組織。', ch:'Ch11', pts:['六要素正確','機械式特徵','有機式特徵','權變因素（策略、規模、技術、環境）']},
    {q:'依 Woodward 的研究，技術如何影響組織結構？', ch:'Ch11', pts:['單件、大量、流程生產','垂直、水平分化、正式化差異','最有效結構']},
    {q:'說明矩陣式結構的優缺點，以及虛擬組織、彈性工時等 21 世紀的彈性安排。', ch:'Ch11', pts:['矩陣：專家跨部門到專案、雙重指揮','優缺點（彈性 vs 違反指揮統一、衝突）','虛擬組織','遠距、壓縮工時、彈性工時、工作分享、臨時人力']}
  ],
  mcq: [
    {q:'"Doing the right things" refers to:', o:['Efficiency','Effectiveness','Productivity','Planning'], a:1, e:'Effectiveness = ends；Efficiency = means（doing things right）。'},
    {q:'Which is NOT one of the four management functions?', o:['Planning','Organizing','Staffing','Controlling'], a:2, e:'POLC：Planning、Organizing、Leading、Controlling。'},
    {q:'Mintzberg 的 "disseminator" 屬於哪一類角色？', o:['Interpersonal','Informational','Decisional','Technical'], a:1, e:'Informational：monitor、disseminator、spokesperson。'},
    {q:'"Negotiator" 屬於：', o:['Interpersonal','Informational','Decisional','Conceptual'], a:2, e:'Decisional：entrepreneur、disturbance handler、resource allocator、negotiator。'},
    {q:'"Liaison" 屬於：', o:['Interpersonal','Informational','Decisional','Human skill'], a:0, e:'Interpersonal：figurehead、leader、liaison。'},
    {q:'高階管理者最需要的技能是：', o:['Technical','Human','Conceptual','Physical'], a:2, e:'Katz：越高層越需要概念技能。'},
    {q:'組織的三個共同特徵不包括：', o:['Distinct purpose','Deliberate structure','People','Profit'], a:3, e:'目的、結構、人。'},
    {q:'決策過程的第 3 步是：', o:['Identify decision criteria','Allocate weights to the criteria','Develop alternatives','Analyze alternatives'], a:1, e:'問題 → 準則 → 權重 → 方案 → 分析 → 選擇 → 執行 → 評估。'},
    {q:'Accepting solutions that are "good enough" is called:', o:['Maximizing','Satisficing','Escalation','Framing'], a:1, e:'有限理性下的滿意解。'},
    {q:'Increased commitment to a previous decision despite evidence it may have been wrong:', o:['Sunk cost','Escalation of commitment','Anchoring','Hindsight'], a:1, e:'14 版。'},
    {q:'程式化決策最常用於：', o:['高階、非結構化問題','基層、結構化問題','新的、不尋常的問題','資訊模糊的問題'], a:1, e:'Exhibit 2.7。'},
    {q:'"A guideline for making decisions" 是：', o:['Procedure','Rule','Policy','Program'], a:2, e:'Procedure = 步驟；Rule = 能/不能；Policy = 指導方針。'},
    {q:'Low tolerance for ambiguity + rational way of thinking =', o:['Directive','Analytic','Conceptual','Behavioral'], a:0, e:'Analytic = 高容忍＋理性；Conceptual = 高容忍＋直覺；Behavioral = 低容忍＋直覺。'},
    {q:'Fixating on initial information as a starting point is:', o:['Anchoring effect','Availability bias','Framing bias','Confirmation bias'], a:0, e:'錨定效應。'},
    {q:'Seeking out information that reaffirms past choices:', o:['Selective perception','Confirmation bias','Self-serving bias','Representation bias'], a:1, e:'確認偏誤。'},
    {q:'Focusing on the most recent events is:', o:['Availability bias','Randomness bias','Hindsight bias','Overconfidence'], a:0, e:'可得性偏誤。'},
    {q:'Mistakenly believing an event could have been predicted after the outcome is known:', o:['Hindsight bias','Self-serving bias','Sunk cost','Framing'], a:0, e:'後見之明。'},
    {q:'Expected value 計算：大雪 $850,000×0.3、普通 $725,000×0.5、小雪 $350,000×0.2，總期望營收為？', o:['$641,667','$687,500','$725,000','$850,000'], a:1, e:'255,000 + 362,500 + 70,000 = 687,500。'},
    {q:'悲觀的管理者在不確定情境下會選擇：', o:['maximax','maximin','minimax regret','expected value'], a:1, e:'選「最小報酬中最大」者。'},
    {q:'A world-oriented view that focuses on using the best approaches from around the globe:', o:['Ethnocentric','Polycentric','Geocentric','Parochial'], a:2, e:'全球中心態度。'},
    {q:'Viewing the world solely through your own perspectives:', o:['Nationalism','Parochialism','Globalization','Polycentrism'], a:1, e:'狹隘主義。'},
    {q:'WTO 實質上取代了：', o:['IMF','GATT','OECD','ASEAN'], a:1, e:'GATT 為 1948 年協定。'},
    {q:'An MNC that decentralizes management decisions to the local country:', o:['Global company','Multidomestic corporation','Transnational','Borderless'], a:1, e:'Global = 集中母國；Transnational = 去除地理界線。'},
    {q:'Giving another organization the right to use your name and operating methods:', o:['Licensing','Franchising','Joint venture','Exporting'], a:1, e:'Licensing 是技術與產品規格。'},
    {q:'A strategic alliance that forms a separate, independent organization:', o:['Joint venture','Foreign subsidiary','Franchise','Global sourcing'], a:0, e:'合資。'},
    {q:'Hofstede 的五構面不包括：', o:['Power distance','Uncertainty avoidance','Humane orientation','Long-term orientation'], a:2, e:'Humane orientation 是 GLOBE 的構面。'},
    {q:'支持全球化的主要理論基礎：', o:['Law of comparative advantage','Law of diminishing returns','Mercantilism','Protectionism'], a:0, e:'每個國家都贏。'},
    {q:"Lewin's three-step process：", o:['Plan, do, check','Unfreeze, change, refreeze','Identify, analyze, act','Start, scale, exit'], a:1, e:'Calm waters metaphor。'},
    {q:'環境缺乏穩定與可預測性，必須持續適應的觀點：', o:['Calm waters','White-water rapids','Status quo','Lewin model'], a:1, e:'激流泛舟。'},
    {q:'當抗拒來自有力群體時，最適合的降低抗拒方法是：', o:['Education','Participation','Negotiation','Facilitation'], a:2, e:'可「買到」承諾，但成本高。'},
    {q:'當抗拒源於錯誤資訊時：', o:['Education and communication','Coercion','Manipulation','Negotiation'], a:0, e:'澄清誤解。'},
    {q:'Taking creative ideas and turning them into useful products is:', o:['Creativity','Innovation','Invention','Design'], a:1, e:'創意 vs 創新。'},
    {q:'Individuals who actively support new ideas and ensure innovations are implemented:', o:['Change agents','Idea champions','Skunk works','Stressors'], a:1, e:'人力資源變數。'},
    {q:'哪一種組織最容易受破壞式創新威脅？', o:['新創公司','大型、成熟、高獲利企業','非營利組織','小型家族企業'], a:1, e:'最捨不得現有市場與技術。'},
    {q:'A small autonomous group within a large organization developing radical innovation:', o:['Matrix team','Skunk works','Cross-functional team','Virtual team'], a:1, e:'臭鼬工廠。'},
    {q:'Type A personality 的特徵：', o:['Relaxed and easygoing','Chronic sense of urgency, excessive competitive drive','Accepts change easily','Low stress'], a:1, e:'Type B 相反。'},
    {q:'策略管理過程中，「內部分析」主要找出：', o:['Opportunities and threats','Strengths and weaknesses','Mission','Competitors'], a:1, e:'外部 = O、T；內部 = S、W。'},
    {q:"An organization's major value-creating capabilities:", o:['Resources','Core competencies','Mission','Business model'], a:1, e:'核心能力 = 競爭武器。'},
    {q:'併購同業競爭者屬於：', o:['Vertical integration','Horizontal integration','Concentration','Diversification'], a:1, e:'垂直整合 = 上下游。'},
    {q:'BCG 矩陣中「低成長、高市佔」為：', o:['Star','Cash cow','Question mark','Dog'], a:1, e:'金牛提供現金。'},
    {q:'BCG 矩陣中「高成長、低市佔」為：', o:['Star','Cash cow','Question mark','Dog'], a:2, e:'問號：決定投資或放棄。'},
    {q:'"Economic moat" 一詞由誰推廣？', o:['Michael Porter','Warren Buffett','Peter Drucker','Henry Mintzberg'], a:1, e:'保護長期利潤與市佔。'},
    {q:'Porter 五力不包括：', o:['Threat of new entrants','Bargaining power of suppliers','Government regulation','Threat of substitutes'], a:2, e:'另兩項：買方議價力、現有競爭。'},
    {q:'Seeking a cost or differentiation advantage in a narrow segment:', o:['Cost leadership','Differentiation','Focus','Stuck in the middle'], a:2, e:'集中策略。'},
    {q:'Private investor offering financial backing in return for equity:', o:['Venture capitalist','Angel investor','IPO','Bank loan'], a:1, e:'VC 是專業管理的資金池。'},
    {q:'哪一種法律形式有雙重課稅？', o:['Sole proprietorship','General partnership','C corporation','LLC'], a:2, e:'公司層級與股東層級皆課稅。'},
    {q:'S corporation 股東人數上限：', o:['35','75','100','無上限'], a:1, e:'Exhibit 10.2。'},
    {q:'Exiting a venture to capitalize financially on the investment:', o:['Liquidation','Harvesting','Turnaround','Retrenchment'], a:1, e:'收割。'},
    {q:'Each person should report to only one manager:', o:['Span of control','Unity of command','Chain of command','Line authority'], a:1, e:'指揮統一。'},
    {q:'Positions created to support, assist, and advise those holding line authority:', o:['Line authority','Staff authority','Responsibility','Empowerment'], a:1, e:'幕僚職權。'},
    {q:'控制幅度越寬，組織通常：', o:['層級越多','層級越少、管理者越少','成本越高','越集權'], a:1, e:'Exhibit 11.4：幅度 8 比 4 少兩層、少約 800 位管理者。'},
    {q:'下列何種情況較適合集權？', o:['環境複雜不確定','公司地理分散','組織面臨危機','基層主管有能力且想參與'], a:2, e:'Exhibit 11.5。'},
    {q:'依 Woodward，大量生產（mass production）最有效的結構是：', o:['Organic','Mechanistic','Matrix','Virtual'], a:1, e:'Unit 與 Process → Organic。'},
    {q:'Little departmentalization, wide spans of control, centralized authority, little formalization:', o:['Simple structure','Functional structure','Divisional structure','Matrix structure'], a:0, e:'簡單結構。'},
    {q:'A small core of full-time employees plus outside specialists hired as needed:', o:['Team structure','Virtual organization','Project structure','Divisional structure'], a:1, e:'又稱 network 或 modular。'},
    {q:'Employees work a specific number of hours a week but are free to vary those hours:', o:['Compressed workweek','Flextime','Job sharing','Telecommuting'], a:1, e:'彈性工時。'},
    {q:'Two or more people split a full-time job:', o:['Job sharing','Flextime','Contingent work','Job rotation'], a:0, e:'工作分享。'}
  ]
};
