// ===== 不動產財管 單元 1 補充：房貸的法律名詞（英美制度＋台灣對照） =====
DATA.re.sections[0].cards.push(
  { id:'re1e', t:'房貸的兩份文件：本票（Promissory Note）與抵押契約（Mortgage）', en:'Promissory note vs mortgage',
    plain:'一筆房貸其實有兩份文件：本票（或借據）證明「你欠錢、承諾還錢」，是債務本身；抵押契約把房子拿來「擔保」這筆債。兩者分開：前者是對人的請求權，後者是對物的擔保權。',
    life:'跟朋友借錢：借據寫「我欠你 10 萬，每月還 1 萬」（本票），另外再寫一張「如果不還，我的機車讓你拿去賣」（抵押）。',
    body:'<h4>Promissory note 本票／借款憑證</h4><ul><li>借款人<b>無條件承諾</b>在特定時間支付特定金額的書面文件，是<b>債務本身</b>（the debt）。</li><li>載明：本金、利率、付款金額與日期、到期日、違約與加速條款、提前還款條款。</li><li>借款人對 note 負<b>個人責任</b>（personal liability）：除非是無追索權貸款，否則房子拍賣不夠還時，貸方可以再向借款人追討。</li><li>Note 可以轉讓（negotiable），次級市場買賣的其實是 note（連同擔保它的 mortgage）。</li></ul><h4>Mortgage 抵押契約</h4><ul><li>把不動產當作 note 的<b>擔保</b>（security instrument），在不動產上設定 <b>lien</b>。</li><li><b>Mortgagor</b> = <b>借款人</b>（提供抵押的人）；<b>Mortgagee</b> = <b>貸方</b>（取得抵押權的人）。容易搞反！</li><li>Mortgage 本身不是債務，沒有 note 就沒有可以擔保的東西（從屬性）。</li><li><b>Mortgage loan</b>（抵押貸款）：以不動產為擔保的貸款 = note + mortgage。</li></ul><h4>Mortgage bond</h4><ul><li>有些州（例如紐約）把借款人的還款承諾稱為 <b>bond</b>，所以房貸文件叫 “bond and mortgage”，功能和 note 相同。</li><li>在公司財務中，<b>mortgage bond</b> 指以不動產為擔保發行的公司債（違約時債權人對該不動產有優先權）。</li></ul><h4>台灣的本票</h4><ul><li><b>票據法 §3</b>：本票是發票人簽發一定金額，於指定到期日由自己<b>無條件支付</b>給受款人或執票人的票據。</li><li><b>票據法 §123</b>：執票人向本票發票人行使追索權時，可以<b>聲請法院裁定後強制執行</b> → 不用經過冗長訴訟，所以貸款、租賃、分期付款常要求簽本票。</li><li>台灣房貸通常包含：借款契約＋本票（部分銀行）＋<b>抵押權設定契約</b>（到地政事務所登記，取得他項權利證明書）。</li></ul>',
    terms:[['promissory note','本票、借款憑證：債務本身'],['mortgage','抵押契約：擔保工具'],['mortgagor','抵押人＝借款人'],['mortgagee','抵押權人＝貸方'],['mortgage loan','抵押貸款 = note + mortgage'],['personal liability','個人責任：可追討借款人其他財產']] },
  { id:'re1f', t:'Lien（留置權／擔保物權）與 Lien Theory vs Title Theory', en:'Liens; lien theory vs title theory',
    plain:'Lien 是債權人在某個財產上的「擔保權利」：債務不還時可以就這個財產優先受償。美國各州對房貸有兩種看法：lien theory 認為房子還是借款人的、貸方只有擔保權；title theory 認為借款期間法律上的所有權（title）在貸方手上，還清才回到借款人。',
    life:'Lien theory：你的手機押給朋友當擔保，但手機還是你的；title theory：手機的「所有權登記」先放在朋友名下，你還清才改回你的名字，但手機一直是你在用。',
    body:'<p>Lien 有很多種（tax lien、judgment lien、mortgage lien、mechanic’s lien……），種類和排序在第 3 組「Lien：種類與順位」詳細整理；這裡先比較美國各州對房貸的兩種法律看法。</p><h4>Lien theory vs Title theory</h4><div class="tblwrap"><table class="tbl"><tr><th></th><th>Lien theory 擔保權說</th><th>Title theory 所有權說</th></tr><tr><td>所有權（title）在誰</td><td><b>借款人</b></td><td>法律所有權（legal title）在<b>貸方</b>，借款人有衡平所有權（equitable title）</td></tr><tr><td>貸方的權利</td><td>只有 lien（擔保權）</td><td>名義上的所有權，借款人還清後依 <b>defeasance clause</b> 取回</td></tr><tr><td>違約時</td><td>貸方要<b>聲請法拍</b>（foreclosure）才能取得房子</td><td>理論上貸方可較快取得占有</td></tr><tr><td>占有使用</td><td>借款人</td><td>借款人（實務上）</td></tr></table></div><ul><li>還有 <b>intermediate theory</b>（中間說）：平常採 lien theory，<b>違約時</b>所有權才移轉給貸方。</li><li>美國多數州採 lien theory。實務上兩者差異已經不大，因為各州法律都保護借款人的贖回權利。</li><li><b>台灣</b>的抵押權類似 lien theory：抵押權<b>不移轉占有、也不移轉所有權</b>，債務不還時抵押權人要聲請法院拍賣。</li></ul>',
    terms:[['lien','以財產擔保債務的權利'],['tax lien','欠稅的留置權，順位通常最優先'],['mechanic’s lien','工程款留置權'],['first / junior lien','第一順位／後順位擔保權'],['recording','登記，決定順位'],['legal vs equitable title','法律所有權 vs 衡平所有權'],['defeasance clause','還清後貸方權利消滅、所有權回到借款人的條款']] },
  { id:'re1g', t:'Deed of Trust：三方的信託契約', en:'Deed of trust',
    plain:'有些州不用一般的 mortgage，而用 deed of trust：借款人把房子的名義所有權交給一個中立的受託人（trustee）保管，貸方是受益人。借款人違約時，受託人可以依契約直接出售房子，不用經過法院，比較快。',
    life:'你和朋友借錢時，把機車的鑰匙交給班導（中立的第三人）保管。你還清，班導把鑰匙還你；你不還，班導可以直接幫朋友把機車賣掉。',
    body:'<ul><li>三方當事人：<ul><li><b>Trustor</b>（信託人）＝ <b>借款人</b>。</li><li><b>Trustee</b>（受託人）＝ 中立第三人（常是產權公司、律師），持有名義上的所有權。</li><li><b>Beneficiary</b>（受益人）＝ <b>貸方</b>。</li></ul></li><li>借款人還清後，trustee 把所有權還給借款人：<b>reconveyance</b>（所有權返還）。</li><li>違約時：契約中的 <b>power of sale</b>（出售權）讓 trustee 可以進行 <b>nonjudicial foreclosure</b>（非訴訟法拍）：依法定程序公告後拍賣，<b>不用經過法院</b> → 時間短、成本低。</li><li>和一般 mortgage 比較：mortgage 是兩方（mortgagor、mortgagee），違約多半要 <b>judicial foreclosure</b>（訴訟法拍）。不過有些州的 mortgage 也可以附 power of sale。</li><li>美國西部很多州（例如加州）常用 deed of trust。</li></ul>',
    terms:[['trustor','信託人＝借款人'],['trustee','受託人＝中立第三人'],['beneficiary','受益人＝貸方'],['reconveyance','還清後返還所有權'],['power of sale','出售權（可非訴訟拍賣）'],['nonjudicial foreclosure','不經法院的法拍']] },
  { id:'re1i', t:'違約與法拍：Default、Foreclosure、贖回權、不足額判決', en:'Default, foreclosure, redemption and deficiency judgments',
    plain:'借款人沒照約定付款就是違約。貸方通常先嘗試協商（展延、修改條件），不行才法拍。法拍前借款人有權還清欠款保住房子；法拍賣的錢不夠還時，有些地方貸方還能向借款人追討差額。',
    life:'手機分期付不出來：店家先打電話問你要不要延後或降低每期金額；真的不行才收回手機拍賣；拍賣價不夠還，店家還可以向你要剩下的錢（有追索權）。',
    body:'<h4>違約後的處理（workouts）</h4><ul><li><b>Forbearance</b>（容忍、暫緩）：暫時減少或停止付款。</li><li><b>Loan modification</b>（修改貸款條件）：降利率、延長期限、本金寬減。</li><li><b>Short sale</b>（短售）：以低於貸款餘額的價格出售，貸方同意接受損失。</li><li><b>Deed in lieu of foreclosure</b>（以屋抵債）：借款人直接把房子移轉給貸方，避免法拍。</li></ul><h4>法拍 Foreclosure</h4><ul><li><b>Judicial foreclosure</b>（訴訟法拍）：貸方向法院起訴，法院判決後拍賣。時間長、成本高。</li><li><b>Power of sale / nonjudicial foreclosure</b>：依契約的出售權，不經法院拍賣（常見於 deed of trust）。</li><li><b>Strict foreclosure</b>（嚴格法拍）：法院直接把所有權判給貸方（少數州）。</li><li>拍賣所得分配順序：法拍費用 → 稅捐 lien → 第一順位房貸 → 後順位 lien → 剩下的給借款人。後順位 lien 若沒受償會被<b>塗銷</b>（wiped out），所以後順位債權人風險高。</li></ul><h4>借款人的贖回權</h4><ul><li><b>Equity of redemption</b>（衡平贖回權）：法拍<b>完成前</b>，借款人付清欠款（含費用）就能保住房子。</li><li><b>Statutory redemption</b>（法定贖回權）：部分州允許在法拍<b>之後</b>一段期間內贖回。</li></ul><h4>Deficiency judgment（不足額判決）</h4><ul><li>拍賣價金不足以清償貸款時，貸方可以請求法院判決借款人支付差額（<b>有追索權</b>貸款）。</li><li><b>Nonrecourse</b>（無追索權）：只能就房子受償，不能再追討借款人 → 借款人可能「策略性違約」。</li></ul><h4>破產 Bankruptcy</h4><ul><li>借款人聲請破產時有<b>自動停止</b>（automatic stay），法拍程序暫停。</li><li>Chapter 7（清算）、Chapter 11（企業重整）、Chapter 13（個人債務重整，可保住房子分期清償）。</li></ul><h4>台灣對照</h4><ul><li>抵押權人聲請法院<b>拍賣抵押物裁定</b> → 強制執行 → 法院拍賣（法拍屋）。</li><li>台灣房貸多為<b>有追索權</b>：拍賣不足的部分，銀行可以繼續向借款人追討。</li></ul>',
    terms:[['default','違約'],['forbearance','暫緩付款'],['loan modification','修改貸款條件'],['short sale','短售'],['deed in lieu of foreclosure','以屋抵債'],['judicial / nonjudicial foreclosure','訴訟／非訴訟法拍'],['equity of redemption','法拍前的贖回權'],['statutory redemption','法拍後的法定贖回權'],['deficiency judgment','不足額判決'],['recourse / nonrecourse','有／無追索權']] },
  { id:'re1j', t:'各種房貸型態：Purchase-money、Junior、Wraparound、Blanket、Land contract', en:'Types of mortgages and financing arrangements',
    plain:'除了一般買房的房貸，還有賣方直接借錢給買方、二胎、一筆貸款擔保多筆土地、把舊貸款包在新貸款裡等不同型態，用在不同的交易情況。',
    life:'買二手車時，賣家說：「頭期款給我，剩下的分期付給我就好」→ 這就是賣方融資（purchase-money mortgage）。',
    body:'<ul><li><b>Purchase-money mortgage</b>（購置價金抵押）：為了購買該不動產而設定的抵押，常指<b>賣方</b>直接提供融資（seller financing），順位通常優先。</li><li><b>Junior / second mortgage</b>（後順位／二胎）：在第一順位之後，利率較高；<b>home equity loan / HELOC</b>（房屋淨值貸款、循環額度）多是二順位。</li><li><b>Wraparound mortgage</b>（包裹式抵押）：新貸款金額包含原本的舊貸款，借款人付款給新貸方，新貸方再繼續繳舊貸款 → 保留舊的低利率（但可能違反 due-on-sale clause）。</li><li><b>Blanket mortgage</b>（總括抵押）：一筆貸款以<b>多筆</b>不動產擔保，常搭配 release clause（例如建商分批賣地）。</li><li><b>Package mortgage</b>：擔保品包含房屋和附屬的家具、設備。</li><li><b>Open-end mortgage</b>：可以在原抵押額度內再借款（future advances），類似台灣的<b>最高限額抵押權</b>。</li><li><b>Construction loan</b>（建築融資）：依工程進度分次撥款，完工後由長期貸款（permanent / take-out loan）取代。</li><li><b>Land contract / installment sales contract</b>（分期付款買賣契約）：買方分期付款給賣方，<b>付清前所有權仍在賣方</b>；買方風險較高。</li><li><b>Reverse mortgage</b>（逆向房貸）：見單元 9。</li></ul>',
    terms:[['purchase-money mortgage','購置價金抵押（常為賣方融資）'],['junior mortgage','後順位抵押'],['HELOC','房屋淨值循環額度'],['wraparound mortgage','包裹式抵押'],['blanket mortgage','總括抵押（多筆不動產）'],['open-end mortgage','可再動用的抵押（類似最高限額）'],['land contract','分期付款買賣，付清才移轉所有權']] },
  { id:'re1k', t:'不動產的權利：Fee simple、Leasehold、Easement、Encumbrance', en:'Property rights and estates',
    plain:'買房買的其實是一組「權利」：可以使用、出租、出售、留給子孫。不同的權利型態（完全所有權、租賃權、地役權等）會影響能不能貸款、能貸多少。',
    life:'買下一間房子（完全所有權）vs 租了一間房子十年（租賃權）vs 鄰居有權從你家院子走過去（地役權）。',
    body:'<ul><li><b>Real property</b>（不動產）：土地及其定著物，以及隨之而來的權利（bundle of rights：占有、使用、收益、處分、排除他人）。</li><li><b>Fee simple absolute</b>（完全所有權）：最完整的所有權，可以無限期持有、出售、繼承 → 最適合當貸款擔保。</li><li><b>Life estate</b>（終身權益）：只在某人生存期間享有，之後回到原所有人或指定的人。</li><li><b>Leasehold</b>（租賃權）：依租約在一定期間內使用他人不動產；貸方對租賃權貸款時，要看剩餘租期。</li><li><b>Easement</b>（地役權）：為了他人土地的便利而使用自己土地的權利（例如通行權）。</li><li><b>Encumbrance</b>（產權負擔）：所有對不動產權利的限制，包括 lien、easement、限制性約定等 → 買房前要做產權調查（title search）。</li><li><b>Title</b>（產權）與 <b>deed</b>（移轉所有權的契據）：warranty deed（賣方保證產權無瑕疵）vs quitclaim deed（只移轉賣方擁有的權利，不做保證）。</li><li><b>台灣對照</b>：所有權、地上權、典權、不動產役權（舊稱地役權）、抵押權；不動產物權要<b>登記</b>才生效（民法 §758）。</li></ul>',
    terms:[['fee simple absolute','完全所有權'],['life estate','終身權益'],['leasehold','租賃權'],['easement','地役權（不動產役權）'],['encumbrance','產權負擔'],['title / deed','產權／移轉契據'],['warranty vs quitclaim deed','保證契據 vs 放棄契據']] }
);

DATA.re.mcq.push(
  { q:'In a mortgage loan, the borrower is called the:', o:['mortgagee','mortgagor','trustee','beneficiary'], a:1, e:'Mortgagor 是提供抵押的借款人；mortgagee 是貸方。' },
  { q:'The document that creates the borrower’s personal obligation to repay the debt is the:', o:['mortgage','promissory note','deed of trust','title insurance policy'], a:1, e:'Promissory note 是債務本身；mortgage／deed of trust 是擔保工具。' },
  { q:'Under lien theory, legal title to the property during the loan is held by the:', o:['lender','borrower','trustee','county recorder'], a:1, e:'Lien theory：所有權在借款人，貸方只有 lien，違約要法拍。Title theory 則是貸方持有法律所有權。' },
  { q:'In a deed of trust, the lender is the:', o:['trustor','trustee','beneficiary','grantor'], a:2, e:'Trustor = 借款人；trustee = 中立第三人；beneficiary = 貸方。' },
  { q:'A power of sale clause allows:', o:['the borrower to sell without paying off the loan','a nonjudicial foreclosure','the lender to raise the interest rate','the borrower to assume another loan'], a:1, e:'有 power of sale，違約時可不經法院拍賣（nonjudicial foreclosure）。' },
  { q:'A clause that makes the entire loan balance immediately due upon default is the:', o:['due-on-sale clause','acceleration clause','subordination clause','release clause'], a:1, e:'Acceleration clause；due-on-sale 是出售房屋時要求還清。' },
  { q:'Hazard insurance required by a mortgage lender mainly protects against:', o:['borrower default','physical damage to the property, such as fire','defects in title','rising interest rates'], a:1, e:'Hazard insurance 保財產損失；PMI 保違約；title insurance 保產權瑕疵。' },
  { q:'Private mortgage insurance (PMI) primarily protects the:', o:['borrower','lender','title company','local government'], a:1, e:'PMI 在借款人違約時補償貸方，通常 LTV > 80% 要求。' },
  { q:'Which lien typically has priority even over a first mortgage?', o:['Mechanic’s lien','Property tax lien','Second mortgage','Judgment lien'], a:1, e:'欠繳房地產稅的 tax lien 通常最優先 → 所以貸方常用 escrow 代繳稅金。' },
  { q:'A borrower’s right to pay off the debt and keep the property before the foreclosure sale is the:', o:['statutory redemption','equity of redemption','deficiency judgment','due-on-sale right'], a:1, e:'Equity of redemption 是法拍前；statutory redemption 是部分州允許法拍後一段期間內贖回。' },
  { q:'When foreclosure proceeds are less than the loan balance on a recourse loan, the lender may seek a:', o:['deficiency judgment','reconveyance','wraparound mortgage','subordination'], a:0, e:'Deficiency judgment：法院判決借款人支付差額；無追索權貸款則不行。' },
  { q:'A mortgage given by the buyer to the seller as part of the purchase price is a:', o:['blanket mortgage','purchase-money mortgage','package mortgage','reverse mortgage'], a:1, e:'Purchase-money mortgage，常見於賣方融資。' },
  { q:'Under a land contract (installment sales contract), title passes to the buyer:', o:['at signing','after the first payment','after the contract is fully paid','never'], a:2, e:'付清前所有權仍在賣方，買方風險較高。' },
  { q:'依票據法，本票執票人向發票人行使追索權時，可以：', o:['直接到地政事務所過戶','聲請法院裁定後強制執行','要求警察扣押財產','不需任何程序直接拍賣房屋'], a:1, e:'票據法 §123：本票可聲請法院裁定後強制執行，比一般訴訟快。' },
  { q:'Buying a property “subject to” the existing mortgage means the buyer:', o:['becomes personally liable for the loan','takes the property without personal liability; the seller remains liable','must pay off the loan immediately','receives a new loan from the lender'], a:1, e:'Subject to：買方不負個人責任；assumption：買方承受並負個人責任。' }
);

// ===== 單元 1 補充（二）：產權與契據、法拍流程（條款與 lien 排序改寫在 d_re3.js） =====
DATA.re.sections[0].cards.push(
  { id:'re1m', t:'Title、Deed、Grantor／Grantee 與 Title assurance', en:'Title, deeds and title assurance',
    plain:'Title 是「所有權」這個法律狀態；deed 是把所有權從賣方（grantor）移轉給買方（grantee）的書面文件。買方和貸方都要確定產權沒有問題，所以要做產權調查、買產權保險，這些方法統稱 title assurance。',
    life:'買二手機車：行照上的名字是所有權（title），過戶文件是 deed，賣方是 grantor、買方是 grantee；去監理站查有沒有被查封或欠罰單，就是 title assurance。',
    body:'<h4>基本名詞</h4><ul><li><b>Title</b>（所有權／產權）：擁有不動產的法律權利，以及證明這個權利的證據。</li><li><b>Deed</b>（契據）：移轉所有權的書面文件。</li><li><b>Grantor</b>（讓與人）：<b>賣方</b>、移轉所有權的人；<b>Grantee</b>（受讓人）：<b>買方</b>、取得所有權的人。（拼法是 grantor，不是 granter）</li><li>有效 deed 的要件：書面、讓與人有行為能力、指明受讓人、法定描述（legal description）、讓與的文字（words of conveyance）、讓與人簽名、<b>交付並受領</b>（delivery and acceptance）；再<b>登記</b>（recording）以對抗第三人。</li></ul><h4>Deed 的種類（保證程度由高到低）</h4><ul><li><b>General warranty deed</b>（一般保證契據）：賣方保證產權完整，包含<b>過去所有人</b>造成的瑕疵。主要保證（covenants）：seisin（確實擁有）、right to convey（有權移轉）、against encumbrances（沒有未揭露的負擔）、quiet enjoyment（不會被第三人主張權利干擾）、warranty forever。</li><li><b>Special warranty deed</b>（特別保證契據）：只保證<b>賣方持有期間</b>沒有產生瑕疵。</li><li><b>Bargain and sale deed</b>：表示賣方擁有產權，但不做保證。</li><li><b>Quitclaim deed</b>（放棄契據）：只移轉賣方「如果有的話」的權利，<b>完全不保證</b>，常用來消除產權疑慮（cloud on title）或家人之間移轉。</li></ul><h4>Title assurance（產權保障）的方法</h4><ul><li><b>Abstract of title ＋ attorney’s opinion</b>：整理該不動產所有登記紀錄的摘要（產權鏈 <b>chain of title</b>），由律師判斷產權是否可交易（<b>marketable title</b>）。缺點：律師只對自己的過失負責，看不到的瑕疵（偽造、未登記的權利）沒有保障。</li><li><b>Title insurance</b>（產權保險）：保險公司調查產權後承保，未來發現瑕疵造成損失由保險理賠。<b>一次付清保費</b>，保障到所有權移轉為止。<ul><li><b>Owner’s policy</b>：保障買方，金額通常是買價。</li><li><b>Lender’s policy</b>（mortgagee’s policy）：保障貸方，金額隨貸款餘額遞減；通常是貸方要求、借款人付費。</li></ul></li><li><b>Torrens system</b>（托崙斯登記制）：政府登記機關直接<b>確認並登記產權</b>，發給產權證書，登記本身就有公信力；美國只有少數地方使用。</li><li><b>Quiet title action</b>（確認產權之訴）：向法院請求確認產權，消除爭議。</li></ul><h4>台灣對照</h4><ul><li>台灣採<b>登記生效＋公信力</b>（類似 Torrens）：不動產物權依法律行為取得、設定、移轉，<b>非經登記不生效力</b>（民法 §758）；信賴登記而取得權利的人受保護（土地法 §43、民法 §759-1）→ 所以台灣幾乎不需要產權保險。</li><li>買賣時查<b>土地及建物登記謄本</b>，看所有權部和<b>他項權利部</b>（抵押權、地上權等）。</li></ul>',
    terms:[['title','所有權／產權'],['deed','移轉所有權的契據'],['grantor / grantee','讓與人（賣方）／受讓人（買方）'],['general warranty deed','一般保證契據'],['special warranty deed','特別保證契據'],['quitclaim deed','放棄契據（不保證）'],['chain of title','產權鏈'],['abstract of title','產權摘要'],['marketable title','可交易的產權'],['title insurance','產權保險'],['Torrens system','托崙斯登記制'],['cloud on title','產權疑慮']] },
  { id:'re1o', t:'Foreclose：法拍的完整流程', en:'The foreclosure process',
    plain:'Foreclose 是貸方在借款人違約後，透過拍賣房子來收回欠款的程序。從違約通知、加速到期、拍賣、分配價金，到買受人取得所有權，每一步都有固定的英文名詞。',
    life:'就像學校處理欠繳的社費：先寄提醒（notice of default）、宣布全部一次繳清（acceleration）、最後把抵押的東西拍賣，賣得的錢先還欠款，剩的才退給你。',
    body:'<ol><li><b>Default</b>（違約）：未依約付款，或違反其他條款（例如沒繳稅、沒保險、未經同意出售）。</li><li><b>Notice of default</b>（違約通知）：通知借款人並給予補救期間（cure period）。</li><li><b>Acceleration</b>（加速到期）：未補救時，貸方依加速條款宣告全部到期。</li><li>協商（workouts）：forbearance、loan modification、short sale、deed in lieu。</li><li><b>Foreclosure</b>（法拍程序）：<ul><li><b>Judicial foreclosure</b>：向法院起訴，登記 <b>lis pendens</b>（訴訟繫屬通知，警告第三人這筆不動產有訴訟），法院判決後由法院人員拍賣（<b>sheriff’s sale</b>）。</li><li><b>Nonjudicial foreclosure</b>：依 power of sale，由受託人公告後拍賣（<b>trustee’s sale</b>）。</li></ul></li><li><b>Foreclosure sale</b>（拍賣）：公開競價；貸方可以用債權金額直接出價（<b>credit bid</b>）。沒人出更高價時，房子由貸方取得，成為 <b>REO</b>（real estate owned，銀行承受的不動產）。</li><li><b>Distribution</b>（價金分配）：依 lien 的順位分配；剩餘款（surplus）給原屋主。</li><li>買受人取得 <b>sheriff’s deed / trustee’s deed</b>。</li><li>之後：<b>statutory redemption</b>（部分州允許的法拍後贖回期間）、<b>deficiency judgment</b>（有追索權時追討不足額）。</li></ol><ul><li>法拍的成本高：法律費用、時間（數月到數年）、房屋閒置貶值、拍賣價通常低於市價 → 貸方常偏好先協商。</li><li><b>Non-recourse loan</b>（無追索權貸款）：貸方只能就房子受償，拍賣不足也不能追討借款人 → 借款人違約的成本較低，貸方會要求較低的 LTV 或較高利率。商用不動產貸款常見 non-recourse（但有 carve-outs，例如詐欺、環境污染時恢復追索）。</li><li><b>台灣</b>：抵押權人聲請<b>拍賣抵押物裁定</b> → 取得執行名義 → 聲請<b>強制執行</b> → 法院查封、鑑價、拍賣（最多數次減價拍賣）→ 分配價金；銀行也可以承受（類似 REO）。</li></ul>',
    terms:[['foreclose / foreclosure','法拍（取消贖回權）'],['notice of default','違約通知'],['cure period','補救期間'],['lis pendens','訴訟繫屬通知'],['sheriff’s sale / trustee’s sale','法院拍賣／受託人拍賣'],['credit bid','以債權金額出價'],['REO','銀行承受的不動產'],['surplus','拍賣剩餘款'],['non-recourse','無追索權']] }
);

DATA.re.mcq.push(
  { q:'A clause allowing additional loans to be secured by the same mortgage is the:', o:['assignment clause','future advances clause','release clause','condemnation clause'], a:1, e:'Future advances clause（追加貸款條款），類似台灣的最高限額抵押權。' },
  { q:'The clause that specifies the order in which a borrower’s payment is applied (e.g., escrow, interest, then principal) is the:', o:['application of payments clause','acceleration clause','due-on-sale clause','prepayment clause'], a:0, e:'Application of payments：每筆付款依序沖抵費用、代管帳戶、利息、本金。' },
  { q:'“Forbearance by lender not a waiver” means that:', o:['the lender must forgive late payments','the lender’s failure to enforce a right once does not waive that right later','the borrower may skip payments','the loan becomes non-recourse'], a:1, e:'貸方一時沒有行使權利，不代表以後放棄。' },
  { q:'An assignment clause allows the:', o:['borrower to transfer the loan to a buyer without approval','lender to sell the note and mortgage to another party','borrower to subordinate the mortgage','lender to raise the interest rate'], a:1, e:'貸方可以轉讓債權（例如賣到次級市場），借款人義務不變。' },
  { q:'When a buyer assumes a loan and the lender releases the original borrower from liability, this is called:', o:['subordination','novation','reconveyance','condemnation'], a:1, e:'Novation（債務更替）：新債務人取代舊債務人。' },
  { q:'After a mortgage is paid off, the lender provides a document releasing its lien, called a:', o:['lis pendens','satisfaction (release) of mortgage','quitclaim deed','notice of default'], a:1, e:'Satisfaction / release of mortgage；deed of trust 則是 reconveyance。台灣是抵押權塗銷。' },
  { q:'In a deed, the party conveying the property is the:', o:['grantee','grantor','mortgagee','beneficiary'], a:1, e:'Grantor = 讓與人（賣方）；grantee = 受讓人（買方）。' },
  { q:'Which deed provides the greatest protection to the buyer?', o:['Quitclaim deed','Special warranty deed','General warranty deed','Bargain and sale deed'], a:2, e:'General warranty deed 保證包含前手造成的瑕疵；quitclaim 完全不保證。' },
  { q:'Which method of title assurance is a one-time premium policy that pays for losses from covered title defects?', o:['Abstract of title','Title insurance','Torrens certificate','Attorney’s opinion'], a:1, e:'Title insurance：owner’s policy 保障買方、lender’s policy 保障貸方。' },
  { q:'Under the Torrens system:', o:['a private insurer guarantees title','title is registered and certified by a government authority','no recording is needed','only lenders are protected'], a:1, e:'政府登記並確認產權，登記有公信力；台灣制度類似。' },
  { q:'Generally, which lien is paid first from foreclosure proceeds (after sale costs)?', o:['The first recorded mortgage','Property tax liens','Judgment liens','Second mortgages'], a:1, e:'房地產稅 lien 通常優先於所有 lien；其他依登記先後。台灣稅捐稽徵法 §6 也規定土增稅、地價稅、房屋稅優先。' },
  { q:'If a senior mortgage is foreclosed, a junior lien on the property is typically:', o:['moved to first priority','wiped out, with any surplus available to it','unaffected and remains on the property','converted to a tax lien'], a:1, e:'前順位法拍後，後順位 lien 被塗銷，只能從剩餘價金受償。' },
  { q:'依民法，同一不動產上的數個抵押權，其次序依：', o:['債權金額大小','登記之先後','借款利率高低','債權人的身分'], a:1, e:'民法 §865：依登記之先後定其次序。' },
  { q:'A notice recorded to warn third parties that a lawsuit (such as a judicial foreclosure) affects the property is a:', o:['lis pendens','deed in lieu','credit bid','subordination agreement'], a:0, e:'Lis pendens（訴訟繫屬通知）。' },
  { q:'Property acquired by the lender at a foreclosure sale is referred to as:', o:['REO (real estate owned)','HELOC','PMI','PITI'], a:0, e:'貸方用 credit bid 得標後持有的不動產稱為 REO。' }
);
