// ===== 公式教室：每個公式拆到每個符號 =====
// tex 用 <v s="key">顯示</v> 標記可點的符號；syms[key] = [中文, English, 白話]
const fx = (n, d = 4) => (Math.round(n * 10 ** d) / 10 ** d).toLocaleString('en-US', { maximumFractionDigits: d });

DATA.deriv.formulas = [
  { id:'F1', t:'遠期／期貨到期收益', en:'Payoff of a forward (or futures) at maturity',
    q:'到期那天，我這張「約好價格」的合約賺多少、賠多少？',
    tex:'多頭 Long：<v s="pay">Payoff</v> = <v s="ST">S<sub>T</sub></v> − <v s="K">K</v>　　空頭 Short：<v s="pay">Payoff</v> = <v s="K">K</v> − <v s="ST">S<sub>T</sub></v>',
    syms:{ pay:['收益（每單位）','payoff (per unit)','到期那天這張合約讓你多賺或少付的錢'], ST:['到期時的現貨價格','spot price at maturity T','到期那天東西「真正」的市價'], K:['交割價／約定價','delivery price','當初講好要用多少錢買賣'] },
    why:'你約好用 K 買。到期時東西值 S<sub>T</sub>。如果 S<sub>T</sub> 比 K 貴，你用便宜的 K 買到值 S<sub>T</sub> 的東西 → 賺 S<sub>T</sub> − K。如果 S<sub>T</sub> 比 K 便宜，你還是得用 K 買 → 虧（數字變負的）。空頭剛好相反，所以兩個人的收益加起來永遠 = 0（零和遊戲）。',
    steps:['先決定你是買方（long）還是賣方（short）','買方：拿「到期市價」減「約定價」','賣方：拿「約定價」減「到期市價」','再乘上合約數量（例如 100 盎司）就是總金額'],
    vars:[{k:'K',s:'K',v:1400,min:1000,max:1800,step:10},{k:'ST',s:'S<sub>T</sub>',v:1300,min:1000,max:1800,step:10},{k:'q',s:'數量',v:100,min:1,max:1000,step:1}],
    calc:v=>`Long：(${v.ST} − ${v.K}) × ${v.q} = <b>${fx((v.ST-v.K)*v.q)}</b><br>Short：(${v.K} − ${v.ST}) × ${v.q} = <b>${fx((v.K-v.ST)*v.q)}</b>`,
    oops:['把 long 和 short 的順序弄反：記「買方希望漲 → S<sub>T</sub> 放前面」','忘了乘合約規模（一口 100 oz）'],
    exam:'The payoff from a long forward position is S<sub>T</sub> − K, and the payoff from a short position is K − S<sub>T</sub>, where K is the delivery price and S<sub>T</sub> is the spot price at maturity.',
    cfa:'CFA Level I Derivatives：forward 的 payoff 與 value 是必考基礎。' },
  { id:'F2', t:'買權 Call 的收益與利潤', en:'Call option payoff and profit',
    q:'買了一個「可以用 K 買」的權利，到期賺多少？',
    tex:'<v s="pay">Payoff</v> = max(<v s="ST">S<sub>T</sub></v> − <v s="K">K</v>, 0)　　<v s="pr">Profit</v> = Payoff − <v s="c">c</v>',
    syms:{ pay:['收益','payoff','到期執行權利拿到的錢（還沒扣成本）'], ST:['到期股價','stock price at expiration','到期那天股票值多少'], K:['執行價','strike / exercise price','你有權用多少錢買'], c:['買權權利金','call premium','買這個權利一開始付的錢'], pr:['利潤','profit','真正賺的：收益扣掉權利金'] },
    why:'<b>max(A, 0)</b> 的意思是「A 和 0 選比較大的那個」。為什麼？因為你是「有權利、沒義務」：股價比 K 高 → 執行，賺 S<sub>T</sub>−K；股價比 K 低 → 不執行，收益就是 0，不會變負的。但當初付的權利金 c 是拿不回來的，所以利潤 = 收益 − c。最多只會虧 c。',
    steps:['算 S<sub>T</sub> − K','如果是負數 → 改成 0（不執行）','收益 − 權利金 = 利潤','損益兩平點：S<sub>T</sub> = K + c'],
    vars:[{k:'K',s:'K',v:100,min:50,max:150,step:5},{k:'ST',s:'S<sub>T</sub>',v:115,min:50,max:160,step:1},{k:'c',s:'c',v:5,min:0,max:20,step:0.5}],
    calc:v=>{const p=Math.max(v.ST-v.K,0);return `max(${v.ST} − ${v.K}, 0) = max(${fx(v.ST-v.K)}, 0) = <b>${fx(p)}</b>${v.ST<v.K?'（不執行）':'（執行）'}<br>Profit = ${fx(p)} − ${v.c} = <b>${fx(p-v.c)}</b>；損益兩平 = ${v.K} + ${v.c} = ${fx(v.K+v.c)}`;},
    oops:['payoff 和 profit 搞混：題目問 profit 才要扣權利金','賣方（short call）的利潤 = c − max(S<sub>T</sub>−K, 0)，最大損失無限'],
    exam:'A long call has a payoff of max(S<sub>T</sub> − K, 0); its profit equals the payoff minus the premium paid. The maximum loss is limited to the premium.',
    cfa:'CFA Level I：option payoff/profit diagrams、breakeven 每年都考。' },
  { id:'F3', t:'賣權 Put 的收益與利潤', en:'Put option payoff and profit',
    q:'買了一個「可以用 K 賣」的權利，到期賺多少？',
    tex:'<v s="pay">Payoff</v> = max(<v s="K">K</v> − <v s="ST">S<sub>T</sub></v>, 0)　　<v s="pr">Profit</v> = Payoff − <v s="p">p</v>',
    syms:{ pay:['收益','payoff','執行賣權拿到的錢'], K:['執行價','strike price','你有權用多少錢賣'], ST:['到期股價','price at expiration','到期那天的市價'], p:['賣權權利金','put premium','買這個保險付的錢'], pr:['利潤','profit','收益扣權利金'] },
    why:'賣權像「保價險」。市價跌到 S<sub>T</sub>，你卻能用比較高的 K 賣出 → 賺 K − S<sub>T</sub>。市價比 K 高的話，你自己去市場賣比較好，不用這個權利 → 收益 0。老師的大頭菜例：保證能 99 鈴錢賣出，就是 K = 99 的 put。',
    steps:['算 K − S<sub>T</sub>','負數 → 0','減掉權利金','損益兩平：S<sub>T</sub> = K − p','最大利潤 = K − p（股價跌到 0）'],
    vars:[{k:'K',s:'K',v:70,min:40,max:120,step:5},{k:'ST',s:'S<sub>T</sub>',v:55,min:0,max:130,step:1},{k:'p',s:'p',v:7,min:0,max:20,step:0.5}],
    calc:v=>{const x=Math.max(v.K-v.ST,0);return `max(${v.K} − ${v.ST}, 0) = <b>${fx(x)}</b><br>Profit = ${fx(x)} − ${v.p} = <b>${fx(x-v.p)}</b>；損益兩平 = ${v.K} − ${v.p} = ${fx(v.K-v.p)}`;},
    oops:['把 K 和 S<sub>T</sub> 順序寫成 call 的樣子','以為 put 是「賣出選擇權」：put 是「賣的權利」，買 put 的人是 long put'],
    exam:'A long put has a payoff of max(K − S<sub>T</sub>, 0). It is used to protect against a fall in the price of the underlying asset.',
    cfa:'CFA：protective put = 股票 + long put，是重要策略。' },
  { id:'F4', t:'每日結算的損益', en:'Daily settlement gain',
    q:'今天收盤後，我的保證金帳戶要加減多少錢？',
    tex:'<v s="g">當日損益</v> = (<v s="Ft">F<sub>t</sub></v> − <v s="F0">F<sub>t−1</sub></v>) × <v s="z">合約規模</v> × <v s="n">口數</v>　（空頭再乘 −1）',
    syms:{ g:['當日損益','daily gain/loss','今天被加進或扣出帳戶的錢'], Ft:['今天結算價','today’s settlement price','今天收盤時大家同意的期貨價'], F0:['昨天結算價','previous settlement price','昨天的結算價（第一天用成交價）'], z:['合約規模','contract size','一口等於多少單位（黃金 100 oz）'], n:['口數','number of contracts','你買了幾口'] },
    why:'期貨不是等到到期才算帳，而是「每天」把今天跟昨天的價差結清（marking to market）。多頭希望價格上漲，所以今天比昨天高就賺；空頭相反。',
    steps:['今天價 − 昨天價（每單位變動）','× 每口幾單位','× 幾口','多頭直接用；空頭變號','加到保證金餘額上'],
    vars:[{k:'F0',s:'F<sub>t−1</sub>',v:1450,min:1300,max:1900,step:0.1},{k:'Ft',s:'F<sub>t</sub>',v:1441,min:1300,max:1900,step:0.1},{k:'z',s:'規模',v:100,min:1,max:5000,step:1},{k:'n',s:'口數',v:2,min:1,max:20,step:1}],
    calc:v=>`Long：(${v.Ft} − ${v.F0}) × ${v.z} × ${v.n} = <b>${fx((v.Ft-v.F0)*v.z*v.n,2)}</b>；Short：<b>${fx(-(v.Ft-v.F0)*v.z*v.n,2)}</b>`,
    oops:['忘記乘口數','把「累積損益」當成「當日損益」'],
    exam:'Futures contracts are marked to market daily: the gain or loss is (F<sub>t</sub> − F<sub>t−1</sub>) × contract size × number of contracts, and it is credited to or debited from the margin account.',
    cfa:'CFA：futures 的 mark-to-market 與 margin 機制。' },
  { id:'F5', t:'保證金追繳的價格', en:'Price that triggers a margin call',
    q:'價格跑到哪裡，我會被叫去補錢？',
    tex:'多頭：<v s="P">P*</v> = <v s="F">F<sub>0</sub></v> − (<v s="IM">IM</v> − <v s="MM">MM</v>) ÷ <v s="z">每口規模</v><br>空頭：<v s="P">P*</v> = <v s="F">F<sub>0</sub></v> + (<v s="IM">IM</v> − <v s="MM">MM</v>) ÷ <v s="z">每口規模</v>',
    syms:{ P:['追繳觸發價','margin call price','價格碰到這裡就要補錢'], F:['成交價','initial futures price','你進場時的期貨價'], IM:['原始保證金（每口）','initial margin','進場要押的錢'], MM:['維持保證金（每口）','maintenance margin','帳戶最低不能低於這條線'], z:['每口規模','contract size','一口幾單位'] },
    why:'IM − MM 是「緩衝墊」：你最多能虧多少錢才會碰到維持線。把這筆錢除以每口的單位數，就變成「每單位價格能動多少」。多頭怕跌，所以從成交價往下扣；空頭怕漲，所以往上加。<br><b>重點</b>：用「每口」的 IM、MM 和「每口」的規模算，口數會被約掉，不影響答案！',
    steps:['緩衝 = IM − MM（例：4,000 − 3,000 = 1,000）','每單位價格緩衝 = 緩衝 ÷ 每口規模（1,000 ÷ 5,000 = 0.20）','判斷方向：long 減、short 加','17.20 + 0.20 = 17.40（課本 2.1，short）','被追繳後要補到「原始」保證金，不是補到維持！'],
    vars:[{k:'F',s:'F<sub>0</sub>',v:17.2,min:1,max:200,step:0.1},{k:'IM',s:'IM',v:4000,min:500,max:20000,step:100},{k:'MM',s:'MM',v:3000,min:0,max:20000,step:100},{k:'z',s:'規模',v:5000,min:1,max:50000,step:100}],
    calc:v=>{const d=(v.IM-v.MM)/v.z;return `緩衝每單位 = (${v.IM} − ${v.MM}) ÷ ${v.z} = ${fx(d)}<br>Long：${v.F} − ${fx(d)} = <b>${fx(v.F-d)}</b>；Short：${v.F} + ${fx(d)} = <b>${fx(v.F+d)}</b>`;},
    oops:['補繳金額補到維持保證金（錯！要補到原始）','用「總」保證金除以「每口」規模（兩邊單位要一致）','多空方向搞反'],
    exam:'A margin call occurs when the balance falls below the maintenance margin. For a short position this happens when the futures price rises by (initial margin − maintenance margin) / contract size.',
    cfa:'CFA：variation margin 的計算題型。' },
  { id:'F6', t:'未平倉量的變化', en:'Change in open interest',
    q:'今天交易完，市場上「還沒平倉的合約」多了還是少了？',
    tex:'Δ<v s="OI">OI</v> = <v s="a">買方開倉</v> − <v s="d">賣方平倉</v> = <v s="c">賣方開倉</v> − <v s="b">買方平倉</v>',
    syms:{ OI:['未平倉量','open interest','市場上還活著的合約數（只算一邊）'], a:['買方開倉','new longs','買的人中，建立新部位的'], b:['買方平倉','longs closing… 其實是空方買回','買的人中，買回來平掉舊空單的'], c:['賣方開倉','new shorts','賣的人中，建立新部位的'], d:['賣方平倉','longs closing out','賣的人中，賣掉平掉舊多單的'] },
    why:'把每筆成交想成「一個買方配一個賣方」。兩個都是新人 → 多一張合約（OI+1）；兩個都在退場 → 少一張（OI−1）；一個進一個出 → 合約換手，數量不變。把所有配對加總，算出來剛好等於「買方開倉 − 賣方平倉」。',
    steps:['成交量 = 買方開 + 買方平 = 賣方開 + 賣方平','代公式：買方開 − 賣方平','驗算：賣方開 − 買方平，答案應該一樣','負數 = OI 減少'],
    vars:[{k:'a',s:'買方開',v:600,min:0,max:5000,step:50},{k:'c',s:'賣方開',v:800,min:0,max:5000,step:50},{k:'vol',s:'成交量',v:2000,min:0,max:10000,step:100}],
    calc:v=>{const b=v.vol-v.a,d=v.vol-v.c;return `買方平 = ${v.vol} − ${v.a} = ${b}；賣方平 = ${v.vol} − ${v.c} = ${d}<br>ΔOI = ${v.a} − ${d} = <b>${v.a-d}</b>（驗算 ${v.c} − ${b} = ${v.c-b}）`;},
    oops:['把成交量直接當 OI 變化','用「買方開 − 買方平」（錯，要交叉：買方開配賣方平）'],
    exam:'Open interest is the total number of contracts outstanding. It went down by 600 because 1,200 longs closed out while only 600 new longs were opened.',
    cfa:'CFA：open interest vs. trading volume 的觀念題。' },
  { id:'F7', t:'基差與避險後的實際價格', en:'Basis and effective hedged price',
    q:'用期貨避險後，我最後實際買到／賣到的價格是多少？',
    tex:'<v s="b">b</v> = <v s="S">S</v> − <v s="F">F</v>　　實際價格 = <v s="F1">F<sub>1</sub></v> + <v s="b2">b<sub>2</sub></v>',
    syms:{ b:['基差','basis','現貨跟期貨的價差'], S:['現貨價','spot price','要避險的那個東西現在的價格'], F:['期貨價','futures price','所用期貨的價格'], F1:['開始避險時的期貨價','futures price when hedge is set up','你鎖定的價格'], b2:['平倉時的基差','basis when hedge is closed out','平倉那天 S<sub>2</sub> − F<sub>2</sub>，事先不知道 → 風險來源'] },
    why:'以 short hedge 為例：你在市場用 S<sub>2</sub> 賣掉東西，期貨部位賺 F<sub>1</sub> − F<sub>2</sub>。加起來 S<sub>2</sub> + F<sub>1</sub> − F<sub>2</sub> = F<sub>1</sub> + (S<sub>2</sub> − F<sub>2</sub>) = <b>F<sub>1</sub> + b<sub>2</sub></b>。F<sub>1</sub> 是已知的，只有 b<sub>2</sub> 不知道，所以叫「基差風險」。到期日平倉時 b<sub>2</sub> = 0（收斂），就能完全鎖在 F<sub>1</sub>。',
    steps:['b<sub>2</sub> = S<sub>2</sub> − F<sub>2</sub>','實際價格 = F<sub>1</sub> + b<sub>2</sub>（買方、賣方都一樣）','賣方：b<sub>2</sub> 越大越好（基差變強有利）','買方：b<sub>2</sub> 越小越好'],
    vars:[{k:'F1',s:'F<sub>1</sub>',v:2.2,min:0,max:100,step:0.05},{k:'S2',s:'S<sub>2</sub>',v:2.0,min:0,max:100,step:0.05},{k:'F2',s:'F<sub>2</sub>',v:1.9,min:0,max:100,step:0.05}],
    calc:v=>`b<sub>2</sub> = ${v.S2} − ${v.F2} = ${fx(v.S2-v.F2)}<br>實際價格 = ${v.F1} + ${fx(v.S2-v.F2)} = <b>${fx(v.F1+v.S2-v.F2)}</b>`,
    oops:['寫成 F − S（定義是 S − F）','以為 long hedge 的公式不一樣：其實也是 F<sub>1</sub> + b<sub>2</sub>'],
    exam:'Basis = spot price − futures price. The effective price obtained with a hedge is F<sub>1</sub> + b<sub>2</sub>; uncertainty about b<sub>2</sub> is called basis risk.',
    cfa:'CFA：basis、convergence、hedging 的概念。' },
  { id:'F8', t:'最小變異避險比率 h*', en:'Minimum variance hedge ratio',
    q:'每 1 單位的現貨，要配多少單位的期貨，風險才最小？',
    tex:'<v s="h">h*</v> = <v s="r">ρ</v> × <v s="sS">σ<sub>S</sub></v> ÷ <v s="sF">σ<sub>F</sub></v>',
    syms:{ h:['最適避險比率','minimum variance hedge ratio','期貨數量 ÷ 現貨數量的最佳比例'], r:['相關係數（rho）','correlation coefficient','現貨與期貨「一起動」的程度，−1 到 1'], sS:['現貨價格變動的標準差（sigma S）','standard deviation of ΔS','現貨價格每期大概晃多大'], sF:['期貨價格變動的標準差','standard deviation of ΔF','期貨價格每期大概晃多大'] },
    why:'想像你用「玩具車」去平衡「真車」的晃動。<br>① 如果兩個完全同步（ρ=1）、晃動一樣大，就 1 比 1。<br>② 期貨晃得比較大（σ<sub>F</sub> 大）→ 少用一點期貨就夠（除以 σ<sub>F</sub>）。<br>③ 現貨晃得比較大 → 要多用一點（乘 σ<sub>S</sub>）。<br>④ 兩者不太同步（ρ 小）→ 期貨幫不了太多，用少一點（乘 ρ）；ρ = 0 時完全不用避險。<br>數學上：讓 ΔS − hΔF 的變異數最小，對 h 微分 = 0 就得到這個公式。',
    steps:['找出三個數：ρ、σ<sub>S</sub>、σ<sub>F</sub>（題目會給）','相乘再相除：ρ × σ<sub>S</sub> ÷ σ<sub>F</sub>','例 3.13：0.7 × 1.2 ÷ 1.4 = 0.6','意思：每 1 磅現貨配 0.6 磅期貨'],
    vars:[{k:'r',s:'ρ',v:0.7,min:0,max:1,step:0.01},{k:'sS',s:'σ<sub>S</sub>',v:1.2,min:0.01,max:5,step:0.01},{k:'sF',s:'σ<sub>F</sub>',v:1.4,min:0.01,max:5,step:0.01}],
    calc:v=>`h* = ${v.r} × ${v.sS} ÷ ${v.sF} = <b>${fx(v.r*v.sS/v.sF)}</b>　剩餘風險 = √(1−ρ²) = ${fx(Math.sqrt(1-v.r*v.r)*100,1)}% 的原本風險`,
    oops:['σ<sub>S</sub>、σ<sub>F</sub> 放反','h*=1 不代表完美避險（3.10）'],
    exam:'The minimum variance hedge ratio is h* = ρσ<sub>S</sub>/σ<sub>F</sub>, where ρ is the correlation between changes in the spot and futures prices.',
    cfa:'CFA Level II/III 會用到 hedge ratio；Level I 先懂概念。' },
  { id:'F9', t:'最適契約口數 N*', en:'Optimal number of contracts',
    q:'知道比例後，到底要買或賣幾口期貨？',
    tex:'<v s="N">N*</v> = <v s="h">h*</v> × <v s="QA">Q<sub>A</sub></v> ÷ <v s="QF">Q<sub>F</sub></v>',
    syms:{ N:['口數','number of contracts','要交易幾口'], h:['避險比率','hedge ratio','上一個公式算出來的'], QA:['要避險的數量','size of position being hedged','你手上（或未來要買賣）多少單位'], QF:['每口期貨的數量','size of one futures contract','一口期貨代表多少單位'] },
    why:'h* × Q<sub>A</sub> = 「需要多少單位的期貨」。但期貨是一口一口賣的，所以再除以一口的大小，就知道要幾口。就像你需要 120,000 磅，一箱 40,000 磅 → 3 箱。',
    steps:['先算 h*','需要的期貨單位 = h* × Q<sub>A</sub>','÷ 每口規模 = 口數','四捨五入到整數','方向：未來要買 → long；未來要賣 → short'],
    vars:[{k:'h',s:'h*',v:0.6,min:0,max:2,step:0.01},{k:'QA',s:'Q<sub>A</sub>',v:200000,min:0,max:5000000,step:1000},{k:'QF',s:'Q<sub>F</sub>',v:40000,min:1,max:100000,step:100}],
    calc:v=>`N* = ${v.h} × ${fx(v.QA)} ÷ ${fx(v.QF)} = <b>${fx(v.h*v.QA/v.QF,2)}</b> ≈ ${Math.round(v.h*v.QA/v.QF)} 口`,
    oops:['忘記乘 h*','沒有說明 long 還是 short'],
    exam:'The optimal number of contracts is N* = h*Q<sub>A</sub>/Q<sub>F</sub>. The beef producer should take a long position in 3 December contracts.',
    cfa:'CFA：number of futures contracts 的計算。' },
  { id:'F10', t:'Tailing the hedge（考慮每日結算）', en:'Tailing the hedge',
    q:'因為期貨每天結算，口數要怎麼調整？',
    tex:'<v s="N">N*</v> = <v s="h">ĥ</v> × <v s="VA">V<sub>A</sub></v> ÷ <v s="VF">V<sub>F</sub></v>',
    syms:{ N:['口數','number of contracts','要幾口'], h:['用一天報酬率算的避險比率','hedge ratio from daily % returns','ρ̂ × σ̂<sub>S</sub>/σ̂<sub>F</sub>，用「百分比報酬」而不是價格變動'], VA:['現貨部位價值','dollar value of position','數量 × 現貨價'], VF:['一口期貨的價值','dollar value of one contract','期貨價 × 合約規模'] },
    why:'差別在「用金額，不用數量」。因為每天結算是用錢算的，所以用部位的「價值」比較精準。當期貨價 ≠ 現貨價時，兩種方法答案會不一樣。遠期沒有每日結算，所以不用 tailing。',
    steps:['V<sub>A</sub> = 數量 × 現貨價','V<sub>F</sub> = 期貨價 × 每口規模','ĥ = ρ̂ × σ̂<sub>S</sub>/σ̂<sub>F</sub>','N = ĥ × V<sub>A</sub>/V<sub>F</sub>'],
    vars:[{k:'h',s:'ĥ',v:1.02,min:0,max:2,step:0.01},{k:'q',s:'數量',v:55000,min:0,max:500000,step:1000},{k:'S',s:'現貨價',v:28,min:1,max:200,step:0.5},{k:'F',s:'期貨價',v:27,min:1,max:200,step:0.5},{k:'z',s:'每口',v:5000,min:1,max:50000,step:100}],
    calc:v=>`V<sub>A</sub> = ${fx(v.q)} × ${v.S} = ${fx(v.q*v.S)}；V<sub>F</sub> = ${v.F} × ${fx(v.z)} = ${fx(v.F*v.z)}<br>N = ${v.h} × ${fx(v.q*v.S)} ÷ ${fx(v.F*v.z)} = <b>${fx(v.h*v.q*v.S/(v.F*v.z),2)}</b>`,
    oops:['V<sub>F</sub> 用現貨價算（要用期貨價）'],
    exam:'When daily settlement is considered, N* = ĥV<sub>A</sub>/V<sub>F</sub>, where V<sub>A</sub> is the dollar value of the position and V<sub>F</sub> is the dollar value of one futures contract.',
    cfa:'進階概念，CFA 較少直接考。' },
  { id:'F11', t:'用指數期貨避險：N* = β V<sub>A</sub>/V<sub>F</sub>', en:'Hedging an equity portfolio with index futures',
    q:'我有一籃子股票，要賣幾口指數期貨才能把市場風險歸零？',
    tex:'<v s="N">N*</v> = <v s="b">β</v> × <v s="VA">V<sub>A</sub></v> ÷ <v s="VF">V<sub>F</sub></v>',
    syms:{ N:['口數','number of contracts','要 short 幾口'], b:['貝他','beta','你的組合比大盤「放大」幾倍；β=1.5 表示大盤漲 1%，你漲約 1.5%'], VA:['組合價值','portfolio value','你的股票總共值多少錢'], VF:['一口期貨價值','futures price × multiplier','指數期貨價 × 乘數（S&P 500 是 $250）'] },
    why:'β = 1 的組合，跟大盤一模一樣，用等值的期貨就能對沖。β = 1.5 的組合，晃動是大盤的 1.5 倍，所以要 1.5 倍的期貨。這裡 β 就是扮演 h* 的角色（因為 β = cov(r<sub>P</sub>, r<sub>M</sub>)/σ<sub>M</sub>²，跟 h* 的定義一樣）。',
    steps:['V<sub>F</sub> = 期貨價 × 乘數（1,000 × 250 = 250,000）','V<sub>A</sub> ÷ V<sub>F</sub> = 5,000,000 ÷ 250,000 = 20','× β：1.5 × 20 = 30','結論：short 30 口'],
    vars:[{k:'b',s:'β',v:1.5,min:0,max:3,step:0.05},{k:'VA',s:'V<sub>A</sub>',v:5000000,min:0,max:500000000,step:100000},{k:'F',s:'期貨價',v:1000,min:1,max:10000,step:10},{k:'m',s:'乘數',v:250,min:1,max:500,step:1}],
    calc:v=>`V<sub>F</sub> = ${fx(v.F)} × ${v.m} = ${fx(v.F*v.m)}<br>N* = ${v.b} × ${fx(v.VA)} ÷ ${fx(v.F*v.m)} = <b>${fx(v.b*v.VA/(v.F*v.m),2)}</b>（short）`,
    oops:['V<sub>F</sub> 忘記乘乘數','忘記乘 β'],
    exam:'To hedge the systematic risk of the portfolio, the company should short N* = βV<sub>A</sub>/V<sub>F</sub> = 30 contracts.',
    cfa:'CFA：beta、systematic risk、equity index futures 都是核心。' },
  { id:'F12', t:'把 β 調到目標 β*', en:'Changing the beta of a portfolio',
    q:'不想歸零，只想把 β 從 1.5 降到 0.75（或升到 2），要幾口？',
    tex:'<v s="N">N</v> = (<v s="bs">β*</v> − <v s="b">β</v>) × <v s="VA">V<sub>A</sub></v> ÷ <v s="VF">V<sub>F</sub></v>　（正數 long、負數 short）',
    syms:{ N:['口數','contracts','正 = 買、負 = 賣'], bs:['目標貝他','target beta','你想要的 β'], b:['目前貝他','current beta','現在的 β'], VA:['組合價值','portfolio value',''], VF:['一口期貨價值','futures price × multiplier',''] },
    why:'每 1 口期貨 short 下去，會把組合的 β 往下拉一點點；long 會往上推。要移動的距離就是 β* − β。移動太多 → 要多一點口數。β = 0 的情況就是上一個公式（N = −β V<sub>A</sub>/V<sub>F</sub>）。',
    steps:['β* − β（例：0.75 − 1.5 = −0.75）','× V<sub>A</sub>/V<sub>F</sub>（× 20）= −15','負數 → short 15 口','升到 2.0：(2 − 1.5) × 20 = +10 → long 10 口'],
    vars:[{k:'b',s:'β',v:1.5,min:0,max:3,step:0.05},{k:'bs',s:'β*',v:0.75,min:0,max:3,step:0.05},{k:'VA',s:'V<sub>A</sub>',v:5000000,min:0,max:500000000,step:100000},{k:'VF',s:'V<sub>F</sub>',v:250000,min:1,max:5000000,step:1000}],
    calc:v=>{const n=(v.bs-v.b)*v.VA/v.VF;return `(${v.bs} − ${v.b}) × ${fx(v.VA)} ÷ ${fx(v.VF)} = <b>${fx(n,2)}</b> → <b>${n<0?'short':'long'} ${Math.abs(Math.round(n))} 口</b>`;},
    oops:['方向弄反：降 β 要賣（short）'],
    exam:'To reduce beta from 1.5 to 0.75, the company should short (1.5 − 0.75) × 5,000,000/250,000 = 15 contracts.',
    cfa:'CFA Level III 常考 adjusting portfolio beta。' }
];

DATA.invest.formulas = [
  { id:'G1', t:'CAPM／證券市場線 SML', en:'Capital Asset Pricing Model',
    q:'一支股票「應該」給我多少報酬，才配得上它的風險？',
    tex:'<v s="E">E(R<sub>i</sub>)</v> = <v s="rf">R<sub>f</sub></v> + <v s="b">β<sub>i</sub></v> × (<v s="RM">E(R<sub>M</sub>)</v> − <v s="rf">R<sub>f</sub></v>)',
    syms:{ E:['預期報酬','expected return','這支股票合理該賺多少 %'], rf:['無風險利率','risk-free rate','放定存／國庫券就能拿到的報酬'], b:['貝他','beta','跟著大盤晃動的倍數（系統風險）'], RM:['市場預期報酬','expected market return','整個大盤預期賺多少'] },
    why:'把報酬想成「排隊的薪水」：<br>① 什麼都不做也拿得到的底薪 = R<sub>f</sub>。<br>② 承擔市場風險的加給 = (E(R<sub>M</sub>) − R<sub>f</sub>)，叫「市場風險溢酬」。<br>③ 你承擔多少倍的市場風險 = β。<br>所以 β = 2 的股票，加給拿 2 倍。只有「分散不掉的風險」（β）才有加給。',
    steps:['市場風險溢酬 = E(R<sub>M</sub>) − R<sub>f</sub>（12% − 5% = 7%）','× β（0.5 × 7% = 3.5%）','+ R<sub>f</sub>（5% + 3.5% = 8.5%）'],
    vars:[{k:'rf',s:'R<sub>f</sub> %',v:5,min:0,max:15,step:0.25},{k:'rm',s:'E(R<sub>M</sub>) %',v:12,min:0,max:30,step:0.25},{k:'b',s:'β',v:0.5,min:-1,max:3,step:0.05}],
    calc:v=>`${v.rf}% + ${v.b} × (${v.rm}% − ${v.rf}%) = ${v.rf}% + ${fx(v.b*(v.rm-v.rf),3)}% = <b>${fx(v.rf+v.b*(v.rm-v.rf),3)}%</b>`,
    oops:['乘 β 時忘記先減 R<sub>f</sub>','CML 用 σ、SML 用 β，別搞混'],
    exam:'According to the CAPM, E(R<sub>i</sub>) = R<sub>f</sub> + β<sub>i</sub>[E(R<sub>M</sub>) − R<sub>f</sub>]; only systematic risk (beta) is rewarded.',
    cfa:'CFA Level I Portfolio Management：CAPM、SML 是超級必考。' },
  { id:'G2', t:'資本市場線 CML', en:'Capital Market Line',
    q:'把錢分配在無風險資產和市場組合之間，風險和報酬的關係？',
    tex:'<v s="E">E(R<sub>p</sub>)</v> = <v s="rf">R<sub>f</sub></v> + [(<v s="RM">E(R<sub>M</sub>)</v> − <v s="rf">R<sub>f</sub></v>) ÷ <v s="sM">σ<sub>M</sub></v>] × <v s="sp">σ<sub>p</sub></v>',
    syms:{ E:['組合預期報酬','expected portfolio return',''], rf:['無風險利率','risk-free rate',''], RM:['市場報酬','market return',''], sM:['市場標準差','market standard deviation','大盤的總風險'], sp:['組合標準差','portfolio standard deviation','你這個組合的總風險'] },
    why:'中括號裡面是「每承擔 1 單位總風險，能多拿多少報酬」，也就是市場的夏普比率（Sharpe ratio）。乘上你的風險 σ<sub>p</sub> 就是你的加給。CML 只適用「有效率的組合」（無風險資產＋市場組合），單一股票要用 SML。',
    steps:['斜率 = (E(R<sub>M</sub>) − R<sub>f</sub>)/σ<sub>M</sub>','× σ<sub>p</sub>','+ R<sub>f</sub>'],
    vars:[{k:'rf',s:'R<sub>f</sub> %',v:2,min:0,max:10,step:0.25},{k:'rm',s:'E(R<sub>M</sub>) %',v:10,min:0,max:30,step:0.25},{k:'sm',s:'σ<sub>M</sub> %',v:20,min:1,max:50,step:1},{k:'sp',s:'σ<sub>p</sub> %',v:10,min:0,max:60,step:1}],
    calc:v=>{const sl=(v.rm-v.rf)/v.sm;return `斜率 = (${v.rm} − ${v.rf}) ÷ ${v.sm} = ${fx(sl)}<br>${v.rf}% + ${fx(sl)} × ${v.sp}% = <b>${fx(v.rf+sl*v.sp,3)}%</b>`;},
    oops:['用 β 代入 CML'],
    exam:'The CML plots expected return against total risk (σ) for efficient portfolios; its slope is the market Sharpe ratio.',
    cfa:'CFA Level I：CML vs SML 比較題常見。' },
  { id:'G3', t:'黃金切割率的價位', en:'Fibonacci retracement levels',
    q:'股價可能在哪裡遇到壓力或支撐？',
    tex:'壓力：<v s="P">P</v> × (1 + <v s="r">r</v>)　　支撐：<v s="P">P</v> × (1 − <v s="r">r</v>)',
    syms:{ P:['基準價','base price','起漲點或高點'], r:['黃金比例','Fibonacci ratio','0.191、0.382、0.5、0.618、0.809'] },
    why:'費波那契數列 1,1,2,3,5,8,13,21,34,55,89,144… 相鄰兩數相除會越來越接近 0.618（55/89、89/144）。隔一個相除接近 0.382（55/144）。0.191 是 0.382 的一半。大家都相信這些比例，所以價格真的常停在這附近（自我實現）。',
    steps:['$10 上漲：10 × 1.191 = 11.91','10 × 1.382 = 13.82','10 × 1.618 = 16.18','$30 下跌：30 × (1 − 0.618) = 11.46'],
    vars:[{k:'P',s:'P',v:10,min:1,max:1000,step:1},{k:'r',s:'r',v:0.618,min:0,max:1,step:0.001}],
    calc:v=>`壓力 ${v.P} × ${fx(1+v.r)} = <b>${fx(v.P*(1+v.r),2)}</b>；支撐 ${v.P} × ${fx(1-v.r)} = <b>${fx(v.P*(1-v.r),2)}</b>`,
    oops:['支撐算成 P × r（要 1 − r）'],
    exam:'Fibonacci levels such as 38.2% and 61.8% are used to identify potential support and resistance.',
    cfa:'技術分析在 CFA 現行課綱比重很低，了解即可。' },
  { id:'G4', t:'移動平均 MA', en:'Moving average',
    q:'最近 T 天的平均價格是多少？',
    tex:'<v s="MA">MA<sub>t</sub></v> = (1/<v s="T">T</v>) × Σ<sub>j=0</sub><sup>T−1</sup> <v s="X">X<sub>t−j</sub></v>',
    syms:{ MA:['移動平均','moving average','最近 T 天收盤價的平均'], T:['天數','number of periods','例如 5 日、20 日（月線）、60 日（季線）、200 日（年線）'], X:['第 t−j 天收盤價','closing price','今天、昨天、前天……'] },
    why:'Σ（sigma）就是「全部加起來」。j 從 0 到 T−1 代表「今天往回數 T 天」。全部加總再除以 T 就是平均。「移動」是因為每天都換掉最舊的一天、加入最新的一天。滾動更新：MA<sub>t+1</sub> = (T × MA<sub>t</sub> + X<sub>t+1</sub> − X<sub>t−T+1</sub>) ÷ T。',
    steps:['列出最近 T 天收盤價','加總','÷ T','明天：加新的一天、扣掉最舊的一天'],
    vars:[{k:'a',s:'第1天',v:50,min:0,max:200,step:0.5},{k:'b',s:'第2天',v:52,min:0,max:200,step:0.5},{k:'c',s:'第3天',v:51,min:0,max:200,step:0.5},{k:'d',s:'第4天',v:54,min:0,max:200,step:0.5},{k:'e',s:'第5天',v:55,min:0,max:200,step:0.5}],
    calc:v=>`MA5 = (${v.a} + ${v.b} + ${v.c} + ${v.d} + ${v.e}) ÷ 5 = <b>${fx((v.a+v.b+v.c+v.d+v.e)/5,2)}</b>`,
    oops:['把 T 天以外的資料也加進來'],
    exam:'A moving average is the average closing price over the last T periods; a golden cross occurs when a short-term MA crosses above a long-term MA.',
    cfa:'了解即可。' },
  { id:'G5', t:'乖離率 Bias', en:'Bias ratio',
    q:'股價離平均線「拉」多遠了？',
    tex:'<v s="B">Bias</v> = (<v s="S">S</v> − <v s="MA">MA<sub>t</sub></v>) ÷ <v s="MA">MA<sub>t</sub></v>',
    syms:{ B:['乖離率','bias','用 % 表示的距離'], S:['目前股價','current price',''], MA:['移動平均','moving average','均線'] },
    why:'像橡皮筋：S − MA 是拉開的長度，除以 MA 變成百分比，這樣高價股和低價股才能比較。拉太長（±7%）就容易彈回去。',
    steps:['S − MA','÷ MA','× 100%','≥ +7% → 買超 → 賣；≤ −7% → 賣超 → 買'],
    vars:[{k:'S',s:'S',v:58,min:1,max:300,step:0.5},{k:'MA',s:'MA',v:54,min:1,max:300,step:0.5}],
    calc:v=>{const b=(v.S-v.MA)/v.MA*100;return `(${v.S} − ${v.MA}) ÷ ${v.MA} = <b>${fx(b,2)}%</b> ${b>=7?'→ 正乖離過大，考慮賣出':b<=-7?'→ 負乖離過大，考慮買進':'→ 正常範圍'}`;},
    oops:['除以 S（要除以 MA）'], exam:'Bias = (S − MA)/MA. A bias above +7% suggests the stock is overbought.', cfa:'了解即可。' },
  { id:'G6', t:'相對強弱指標 RSI', en:'Relative Strength Index',
    q:'最近這幾天，漲的力量佔多少？',
    tex:'<v s="RSI">RSI</v> = 100 − 100 ÷ (1 + <v s="RS">RS</v>)，<v s="RS">RS</v> = <v s="U">平均上漲</v> ÷ <v s="D">平均下跌</v>',
    syms:{ RSI:['相對強弱指標','RSI','0～100'], RS:['相對強弱','relative strength','漲的力量 ÷ 跌的力量'], U:['i 日內平均上漲幅度','average gain','只算上漲的天'], D:['i 日內平均下跌幅度','average loss','只算下跌的天（取正值）'] },
    why:'兩個寫法其實一樣：RSI = 100 × 上漲 ÷ (上漲 + 下跌)。如果這幾天都在漲，下跌 = 0 → RSI = 100；都在跌 → RSI = 0。漲久必跌、跌久必漲，所以 RSI 很高（約 80）考慮賣、很低（約 20）考慮買。',
    steps:['算每天漲跌：今天 − 昨天','把正的加起來 = 上漲總和','把負的取絕對值加起來 = 下跌總和','RSI = 100 × 上漲 ÷ (上漲 + 下跌)'],
    vars:[{k:'U',s:'上漲總和',v:6,min:0,max:50,step:0.1},{k:'D',s:'下跌總和',v:2,min:0,max:50,step:0.1}],
    calc:v=>`RS = ${v.U} ÷ ${v.D} = ${v.D?fx(v.U/v.D,3):'∞'}<br>RSI = 100 × ${v.U} ÷ (${v.U} + ${v.D}) = <b>${v.U+v.D?fx(100*v.U/(v.U+v.D),1):50}</b>`,
    oops:['下跌忘記取正值'], exam:'RSI = 100 − 100/(1 + RS). An RSI above 80 indicates overbought conditions.', cfa:'了解即可。' },
  { id:'G7', t:'KD 隨機指標', en:'Stochastic oscillator (K and D)',
    q:'今天的收盤價，落在最近 n 天最高和最低之間的哪個位置？',
    tex:'<v s="RSV">RSV<sub>t</sub></v> = (<v s="C">C<sub>t</sub></v> − <v s="L">L<sub>n</sub></v>) ÷ (<v s="H">H<sub>n</sub></v> − <v s="L">L<sub>n</sub></v>) × 100<br><v s="K">K<sub>t</sub></v> = ⅓ RSV<sub>t</sub> + ⅔ K<sub>t−1</sub>　　<v s="Dd">D<sub>t</sub></v> = ⅓ K<sub>t</sub> + ⅔ D<sub>t−1</sub>',
    syms:{ RSV:['未成熟隨機值','raw stochastic value','今天位置的百分比'], C:['今天收盤','close',''], L:['n 天最低','lowest low',''], H:['n 天最高','highest high',''], K:['快速指標 K','%K','RSV 平滑後'], Dd:['慢速指標 D','%D','K 再平滑一次'] },
    why:'RSV 像「今天成績在最近 9 次考試中的 PR 值」：考到最高分 = 100，考到最低 = 0。但每天跳來跳去太敏感，所以 K 只拿今天的 ⅓、保留昨天 K 的 ⅔（像加權平均，讓線變平滑）。D 再對 K 做一次一樣的事，更平滑、更慢。K 從下往上穿過 D → 買；高檔 K 跌破 D → 賣。沒有前一天就用 50。',
    steps:['RSV = (C − L) ÷ (H − L) × 100','K = RSV/3 + 昨天K × 2/3','D = K/3 + 昨天D × 2/3','判斷：KD > 80 過熱、< 20 超賣'],
    vars:[{k:'C',s:'C',v:57,min:0,max:200,step:0.5},{k:'H',s:'H',v:60,min:0,max:200,step:0.5},{k:'L',s:'L',v:50,min:0,max:200,step:0.5},{k:'K0',s:'昨天K',v:50,min:0,max:100,step:1},{k:'D0',s:'昨天D',v:50,min:0,max:100,step:1}],
    calc:v=>{const r=v.H===v.L?50:(v.C-v.L)/(v.H-v.L)*100;const K=r/3+v.K0*2/3;const D=K/3+v.D0*2/3;return `RSV = (${v.C} − ${v.L}) ÷ (${v.H} − ${v.L}) × 100 = ${fx(r,1)}<br>K = ${fx(r,1)}/3 + ${v.K0}×2/3 = <b>${fx(K,1)}</b>；D = ${fx(K,1)}/3 + ${v.D0}×2/3 = <b>${fx(D,1)}</b>`;},
    oops:['K 和 D 的權重放反'], exam:'%K measures where the close lies within the recent high–low range; %D is a moving average of %K.', cfa:'了解即可。' },
  { id:'G8', t:'本益比 P/E', en:'Price-to-earnings ratio',
    q:'用現在的價格買，要幾年的獲利才能「回本」？',
    tex:'<v s="PE">P/E</v> = <v s="P">股價</v> ÷ <v s="E">每股盈餘 EPS</v>',
    syms:{ PE:['本益比','P/E ratio','股價是盈餘的幾倍'], P:['股價','price per share',''], E:['每股盈餘','earnings per share','公司一年每股賺多少'] },
    why:'P/E = 20 代表「花 20 元買每年賺 1 元的東西」，大約 20 年回本。1990 年日本股市 P/E 超過 60、網路泡沫時那斯達克 P/E 超過 100（或根本沒有盈餘）→ 價格遠超過盈餘能支撐的程度，就是泡沫的訊號。',
    steps:['找股價','找 EPS','相除'],
    vars:[{k:'P',s:'股價',v:600,min:1,max:3000,step:1},{k:'E',s:'EPS',v:10,min:0.1,max:200,step:0.1}],
    calc:v=>`${v.P} ÷ ${v.E} = <b>${fx(v.P/v.E,1)} 倍</b>`,
    oops:['EPS 為負時 P/E 沒有意義'], exam:'A P/E ratio of 60 means investors pay 60 times current earnings, which signals extreme valuation.', cfa:'CFA Level I Equity：P/E 是最基本的估值倍數。' }
];

DATA.mgmt.formulas = [
  { id:'H1', t:'加權評分（決策步驟 3–6）', en:'Weighted scoring of alternatives',
    q:'有好幾個選項、好幾個標準，怎麼算出哪個最好？',
    tex:'<v s="T">Total</v> = Σ (<v s="w">weight<sub>i</sub></v> × <v s="s">score<sub>i</sub></v>)',
    syms:{ T:['總分','total weighted score','這個方案的最後分數'], w:['準則權重','criterion weight','這個標準有多重要（10 = 最重要）'], s:['方案在該準則的評分','rating on criterion i','這台電腦在這個項目得幾分'] },
    why:'Σ 就是「全部加起來」。每個標準先乘上它的重要程度，再全部加總。像學期成績：期中 30%、期末 40%、作業 30%，各自乘完再加。Amanda 的筆電：Memory 10 × 10 + Battery 8 × 7 + Weight 6 × 8 + Warranty 4 × 6 + Display 3 × 7 = 249。',
    steps:['列出準則與權重','每個方案在每個準則打分','分數 × 權重','全部加總','選最高分'],
    vars:[{k:'s1',s:'Memory 分',v:10,min:0,max:10,step:1},{k:'s2',s:'Battery 分',v:7,min:0,max:10,step:1},{k:'s3',s:'Weight 分',v:8,min:0,max:10,step:1},{k:'s4',s:'Warranty 分',v:6,min:0,max:10,step:1},{k:'s5',s:'Display 分',v:7,min:0,max:10,step:1}],
    calc:v=>`10×${v.s1} + 8×${v.s2} + 6×${v.s3} + 4×${v.s4} + 3×${v.s5} = <b>${10*v.s1+8*v.s2+6*v.s3+4*v.s4+3*v.s5}</b>`,
    oops:['忘記乘權重直接加'], exam:'Each alternative is scored on each criterion, the scores are multiplied by the criterion weights, and the alternative with the highest total is selected.', cfa:'' },
  { id:'H2', t:'期望值 Expected value', en:'Expected value (decision under risk)',
    q:'結果不確定、但知道機率時，平均能賺多少？',
    tex:'<v s="EV">EV</v> = Σ (<v s="p">p<sub>i</sub></v> × <v s="x">x<sub>i</sub></v>)',
    syms:{ EV:['期望值','expected value','長期平均下來會得到多少'], p:['機率','probability','這種情況發生的機會，全部加起來 = 1'], x:['報酬','payoff / revenue','這種情況發生時賺多少'] },
    why:'想像同一件事重複發生 10 次：3 次大雪、5 次普通、2 次小雪。平均每次賺 = (3×850,000 + 5×725,000 + 2×350,000)/10 = 687,500。這就是每種結果「乘上機率」再加總。',
    steps:['確認機率加總 = 1','每個結果 × 機率','加總'],
    vars:[{k:'x1',s:'大雪營收',v:850000,min:0,max:2000000,step:5000},{k:'p1',s:'大雪機率',v:0.3,min:0,max:1,step:0.05},{k:'x2',s:'普通營收',v:725000,min:0,max:2000000,step:5000},{k:'p2',s:'普通機率',v:0.5,min:0,max:1,step:0.05},{k:'x3',s:'小雪營收',v:350000,min:0,max:2000000,step:5000}],
    calc:v=>{const p3=+(1-v.p1-v.p2).toFixed(2);return `小雪機率 = 1 − ${v.p1} − ${v.p2} = ${p3}<br>EV = ${fx(v.x1)}×${v.p1} + ${fx(v.x2)}×${v.p2} + ${fx(v.x3)}×${p3} = <b>${fx(v.x1*v.p1+v.x2*v.p2+v.x3*p3,0)}</b>`;},
    oops:['機率加總不是 1'], exam:'Under risk, managers calculate expected value by multiplying each outcome by its probability and summing the results.', cfa:'CFA Quant：expected value 是機率的基礎。' },
  { id:'H3', t:'遺憾值 Regret（不確定情境）', en:'Regret matrix (minimax regret)',
    q:'如果選錯了，最多會後悔多少？',
    tex:'<v s="R">Regret<sub>ij</sub></v> = <v s="M">max<sub>i</sub> payoff<sub>ij</sub></v> − <v s="x">payoff<sub>ij</sub></v>',
    syms:{ R:['遺憾值','regret','早知道對手會這樣做，你本來可以多賺多少'], M:['該欄最大報酬','best payoff for that state','對手採取行動 j 時，最好的策略能賺多少'], x:['你的策略報酬','payoff of strategy i','你選的策略在那種情況賺多少'] },
    why:'對每一種「對手的行動」（每一欄），先找出最好的結果，再看你的選擇跟最好差多少。每個策略找出「最多後悔多少」，最後選那個「最大後悔最小」的。Visa 例：每欄最大 24、21、28 → S4 最大遺憾只有 7 → 選 S4。',
    steps:['每欄找最大值','最大值 − 每格 = 遺憾','每列找最大遺憾','選最大遺憾最小的那列'],
    vars:[{k:'m',s:'該欄最大',v:28,min:0,max:100,step:1},{k:'x',s:'你的報酬',v:11,min:0,max:100,step:1}],
    calc:v=>`Regret = ${v.m} − ${v.x} = <b>${v.m-v.x}</b>`,
    oops:['用「列」的最大值減（要用欄）'], exam:'A manager who wants to minimize maximum regret computes the regret for each cell and chooses the strategy with the smallest maximum regret.', cfa:'' }
];
